/* Biochemistry 互動式考題 — 題庫資料（中英雙語）
 * Bilingual question bank for "Biochemistry Interactive Tutorial"
 * type: "single" | "multi" | "tf"
 * single ans: "A"|"B"|"C"|"D"
 * multi  ans: ["A","C"]
 * tf     ans: "T"|"F"
 * 18 chapters × 10 Q = 180 Q
 */
window.QUIZ_DATA = {
  biochem: {
    label: "Biochemistry 互動考題",
    label_en: "Biochemistry Interactive Quiz",
    chapters: [
      {
        id: "ch01", title: "Ch.1 水、pH 與弱作用力", title_en: "Ch.1 Water, pH & Weak Interactions",
        block: "A", questions: [
          {type:"single", stem:"水的高介電常數 (78.5) 主要的生物學意義？", stem_en:"The biological significance of water's high dielectric constant (78.5)?",
            A:"使水沸點高", A_en:"Raises water's boiling point",
            B:"屏蔽帶電基團的庫倫力 ~78 倍，幫助離子溶解", B_en:"Screens charge-charge Coulomb forces by ~78×, helping ions dissolve",
            C:"讓蛋白質摺疊", C_en:"Causes protein folding",
            D:"水可以結冰", D_en:"Allows water to freeze",
            ans:"B", exp:"高介電常數讓水溶液中鹽橋變弱、蛋白疏水核心內鹽橋變強。", exp_en:"High ε weakens salt bridges in aqueous solution and strengthens them in protein hydrophobic interiors."},
          {type:"single", stem:"緩衝液在哪裡最有效？", stem_en:"A buffer is most effective when?",
            A:"pH = 7", A_en:"pH = 7",
            B:"pH 遠離 pKa", B_en:"pH far from pKa",
            C:"pH = pKa（[A⁻] = [HA]）", C_en:"pH = pKa (where [A⁻] = [HA])",
            D:"pH 極端值", D_en:"At extreme pH values",
            ans:"C", exp:"Henderson-Hasselbalch 給出 pH = pKa 時兩種形式等比例，緩衝容量最大。", exp_en:"Henderson-Hasselbalch shows maximum buffer capacity at pH = pKa where [HA] = [A⁻]."},
          {type:"single", stem:"疏水效應的真正驅動力是？", stem_en:"The real driving force of the hydrophobic effect is?",
            A:"非極性分子相互吸引", A_en:"Nonpolar molecules attract each other",
            B:"共價鍵形成", B_en:"Covalent bond formation",
            C:"水分子重新獲得熵（不再排成籠狀）", C_en:"Water gains entropy (no longer caged)",
            D:"靜電吸引", D_en:"Electrostatic attraction",
            ans:"C", exp:"非極性分子聚集釋放被困住的水分子，是熵驅動而非分子吸引。", exp_en:"Clustering nonpolar molecules releases trapped waters — entropy-driven, not attraction-driven."},
          {type:"single", stem:"血液 pH 維持在 7.35–7.45 主要靠哪個系統？", stem_en:"Blood pH (7.35–7.45) is mainly maintained by which system?",
            A:"乳酸-丙酮酸", A_en:"Lactate-pyruvate",
            B:"碳酸-碳酸氫鹽（CO₂/HCO₃⁻）", B_en:"Carbonic acid-bicarbonate (CO₂/HCO₃⁻)",
            C:"磷酸-磷酸鹽", C_en:"Phosphate",
            D:"氨-氨基", D_en:"Ammonia",
            ans:"B", exp:"碳酸氫鹽緩衝是「開放系統」——肺調 CO₂、腎調 HCO₃⁻，可大範圍緩衝。", exp_en:"Bicarbonate is an open system — lungs adjust CO₂, kidneys adjust HCO₃⁻, giving wide buffering range."},
          {type:"single", stem:"37°C 下做酶反應，下列何種緩衝最不適合？", stem_en:"For an enzyme assay at 37°C, which buffer is least suitable?",
            A:"HEPES (pKa 7.5)", A_en:"HEPES (pKa 7.5)",
            B:"Tris（ΔpKa/ΔT ≈ −0.028）", B_en:"Tris (ΔpKa/ΔT ≈ −0.028)",
            C:"PIPES", C_en:"PIPES",
            D:"Phosphate", D_en:"Phosphate",
            ans:"B", exp:"Tris pKa 對溫度極敏感，37°C 時 pKa 顯著下降，4°C 配製、37°C 反應會偏移近 1 pH。", exp_en:"Tris pKa is very temperature-sensitive — preparing at 4°C and assaying at 37°C can shift pH ~1 unit."},
          {type:"single", stem:"H 鍵的典型能量範圍？", stem_en:"Typical H-bond energy range?",
            A:"~1 kJ/mol（van der Waals）", A_en:"~1 kJ/mol (van der Waals)",
            B:"~5–30 kJ/mol", B_en:"~5–30 kJ/mol",
            C:"~400 kJ/mol（共價鍵）", C_en:"~400 kJ/mol (covalent)",
            D:"~1000 kJ/mol", D_en:"~1000 kJ/mol",
            ans:"B", exp:"H 鍵介於弱 van der Waals 與強共價之間，生命剛好用對這種「中等強度」力。", exp_en:"H-bonds sit between weak vdW and strong covalent — life uses this Goldilocks energy."},
          {type:"multi", stem:"哪些屬於非共價作用力？（多選）", stem_en:"Which are non-covalent interactions? (multi)",
            A:"氫鍵", A_en:"H-bond",
            B:"離子鍵 / 鹽橋", B_en:"Ionic / salt bridge",
            C:"van der Waals", C_en:"van der Waals",
            D:"雙硫鍵", D_en:"Disulfide bond",
            ans:["A","B","C"], exp:"雙硫鍵是共價鍵；前三者皆為非共價。", exp_en:"Disulfide is covalent; the others are non-covalent."},
          {type:"multi", stem:"下列何者可改變細胞內 ATP 水解的實際 ΔG？（多選）", stem_en:"Which change cellular ΔG of ATP hydrolysis? (multi)",
            A:"溫度", A_en:"Temperature",
            B:"[ATP]/[ADP][Pi] 比例", B_en:"[ATP]/[ADP][Pi] ratio",
            C:"Mg²⁺ 濃度", C_en:"[Mg²⁺]",
            D:"標準狀態 ΔG°' 公定值改變", D_en:"Change to standard ΔG°'",
            ans:["A","B","C"], exp:"ΔG = ΔG°' + RT ln Q，受溫度、濃度比、Mg²⁺ 影響；ΔG°' 本身是常數。", exp_en:"ΔG = ΔG°' + RT ln Q. T, ratios, and Mg²⁺ all affect Q; ΔG°' itself is a constant."},
          {type:"tf", stem:"pH 7 的純水中 [H⁺] = 0。", stem_en:"At pH 7, pure water has [H⁺] = 0.",
            ans:"F", exp:"pH 7 意指 [H⁺] = 10⁻⁷ M，不是零。", exp_en:"pH 7 means [H⁺] = 10⁻⁷ M, not zero."},
          {type:"tf", stem:"疏水效應主要由分子間的「吸引力」造成。", stem_en:"The hydrophobic effect is primarily caused by molecular attraction.",
            ans:"F", exp:"疏水效應是熵驅動：水分子釋放回到自由液體狀態。", exp_en:"Hydrophobic effect is entropy-driven — water molecules released from cage structures."},
        ]
      },
      {
        id: "ch02", title: "Ch.2 胺基酸與蛋白質結構", title_en: "Ch.2 Amino Acids & Protein Structure",
        block: "A", questions: [
          {type:"single", stem:"哪個胺基酸在生理 pH 下能扮演「質子穿梭」角色？", stem_en:"Which AA serves as a proton shuttle at physiological pH?",
            A:"Alanine", A_en:"Alanine", B:"Glycine", B_en:"Glycine",
            C:"Histidine（pKa ≈ 6.0）", C_en:"Histidine (pKa ≈ 6.0)", D:"Leucine", D_en:"Leucine",
            ans:"C", exp:"His pKa ≈ 6.0，生理 pH 半質子化，可吸放質子。", exp_en:"His pKa ≈ 6.0 — half-protonated at physiological pH, can donate/accept protons."},
          {type:"single", stem:"α 螺旋的典型 (φ, ψ)？", stem_en:"Typical (φ, ψ) of α-helix?",
            A:"(+60°, +45°)", A_en:"(+60°, +45°)", B:"(-60°, -45°)", B_en:"(-60°, -45°)",
            C:"(-120°, +120°)", C_en:"(-120°, +120°)", D:"(+180°, -180°)", D_en:"(+180°, -180°)",
            ans:"B", exp:"右手 α 螺旋骨架角約 (-60°, -45°)。", exp_en:"Right-handed α-helix backbone angles are around (-60°, -45°)."},
          {type:"single", stem:"280 nm UV 吸光主要由哪些殘基貢獻？", stem_en:"UV 280 nm absorbance is dominated by?",
            A:"Lys、Arg", A_en:"Lys, Arg",
            B:"所有胺基酸同等貢獻", B_en:"All AAs equally",
            C:"Trp、Tyr（與少量 Cys-Cys）", C_en:"Trp, Tyr (small contribution from Cys-Cys)",
            D:"Gly、Ala", D_en:"Gly, Ala",
            ans:"C", exp:"ε(Trp)=5500, ε(Tyr)=1490, ε(Cys-Cys)=125 M⁻¹cm⁻¹。", exp_en:"ε(Trp)=5500, ε(Tyr)=1490, ε(Cys-Cys)=125 M⁻¹cm⁻¹."},
          {type:"single", stem:"Anfinsen 實驗的核心結論？", stem_en:"Anfinsen's key conclusion?",
            A:"蛋白質需要伴隨蛋白才能摺疊", A_en:"Proteins need chaperones to fold",
            B:"一級結構完全決定後續層級", B_en:"Primary structure determines all higher levels",
            C:"摺疊需要 ATP", C_en:"Folding needs ATP",
            D:"摺疊隨機", D_en:"Folding is random",
            ans:"B", exp:"Anfinsen (1972 Nobel)：序列即足以決定天然構象。", exp_en:"Anfinsen (1972 Nobel): sequence alone determines native conformation."},
          {type:"single", stem:"β 折疊（β-sheet）主要由什麼穩定？", stem_en:"β-sheets are stabilized mainly by?",
            A:"側鏈間共價鍵", A_en:"Side-chain covalent bonds",
            B:"骨架氫鍵（鏈間 C=O…H–N）", B_en:"Backbone H-bonds (C=O…H–N between strands)",
            C:"金屬橋", C_en:"Metal bridges",
            D:"疏水交互作用", D_en:"Hydrophobic interactions only",
            ans:"B", exp:"β 折疊靠鏈間骨架氫鍵連接。", exp_en:"β-sheets are held by inter-strand backbone H-bonds."},
          {type:"single", stem:"下列哪個殘基最常出現在 turn / loop？", stem_en:"Which residue is most common in turns/loops?",
            A:"Val", A_en:"Val", B:"Leu", B_en:"Leu", C:"Gly 與 Pro", C_en:"Gly and Pro", D:"Trp", D_en:"Trp",
            ans:"C", exp:"Gly 提供靈活性、Pro 限制方向；兩者都頻繁出現在 turns。", exp_en:"Gly provides flexibility, Pro restricts direction — both frequent in turns."},
          {type:"multi", stem:"以下何者是錯誤摺疊相關疾病？（多選）", stem_en:"Which are misfolding-related diseases? (multi)",
            A:"Alzheimer's (Aβ, Tau)", A_en:"Alzheimer's (Aβ, Tau)",
            B:"Parkinson's (α-synuclein)", B_en:"Parkinson's (α-synuclein)",
            C:"Huntington's (poly-Q)", C_en:"Huntington's (poly-Q)",
            D:"急性盲腸炎", D_en:"Acute appendicitis",
            ans:["A","B","C"], exp:"急性盲腸炎與蛋白摺疊無關。", exp_en:"Appendicitis is not a protein misfolding disease."},
          {type:"multi", stem:"哪些殘基典型出現在蛋白「疏水核心」？（多選）", stem_en:"Which residues typically populate hydrophobic core? (multi)",
            A:"Leu", A_en:"Leu", B:"Lys", B_en:"Lys", C:"Phe", C_en:"Phe", D:"Asp", D_en:"Asp",
            ans:["A","C"], exp:"Leu、Phe 是疏水殘基；Lys 與 Asp 帶電通常在表面。", exp_en:"Leu/Phe are hydrophobic; Lys/Asp are charged surface residues."},
          {type:"tf", stem:"蛋白質的一級結構足以決定其天然 3D 結構（Anfinsen 假說）。", stem_en:"Primary structure alone determines native 3D fold (Anfinsen).",
            ans:"T", exp:"在缺乏額外因子下，許多球狀蛋白可自摺疊。", exp_en:"Many globular proteins self-fold without extra factors."},
          {type:"tf", stem:"Pro 在多肽中可作為 α 螺旋的「破壞者」。", stem_en:"Pro acts as an α-helix breaker.",
            ans:"T", exp:"Pro 環狀側鏈限制 φ 角，常打斷 α 螺旋。", exp_en:"Pro's ring constrains φ, often breaking α-helix."},
        ]
      },
      {
        id: "ch03", title: "Ch.3 結構解析方法與 AlphaFold 3", title_en: "Ch.3 Structure Methods & AlphaFold 3",
        block: "A", questions: [
          {type:"single", stem:"AlphaFold 3 相較 AlphaFold 2 最大的能力差別？", stem_en:"AF3 vs AF2 main capability leap?",
            A:"快 1000 倍", A_en:"1000× faster",
            B:"達原子解析度", B_en:"Atomic resolution",
            C:"可預測蛋白-核酸-小分子-離子聯合複合物（用擴散模型）", C_en:"Predicts protein-NA-ligand-ion complexes (diffusion)",
            D:"不需序列輸入", D_en:"No sequence input",
            ans:"C", exp:"AF3 (Nature 2024) 用擴散模型擴展到核酸、配體、離子、修飾殘基。", exp_en:"AF3 (Nature 2024) uses diffusion to predict NA, ligands, ions, modified residues."},
          {type:"single", stem:"100 kDa 膜蛋白 GPCR 與配體複合物最佳結構方法？", stem_en:"100 kDa GPCR-ligand complex — best method?",
            A:"NMR", A_en:"NMR",
            B:"Cryo-EM（nanodisc 或 detergent）", B_en:"Cryo-EM (nanodisc/detergent)",
            C:"AlphaFold 直接相信", C_en:"Trust AlphaFold directly",
            D:"SAXS", D_en:"SAXS",
            ans:"B", exp:"2025 後絕大多數 GPCR 結構由 cryo-EM 解析。", exp_en:"Post-2025, the vast majority of GPCR structures come from cryo-EM."},
          {type:"single", stem:"pLDDT 分數的意義？", stem_en:"What does pLDDT measure?",
            A:"解析度", A_en:"Resolution",
            B:"配體親和力", B_en:"Ligand affinity",
            C:"訓練集大小", C_en:"Training set size",
            D:"每殘基局部信心；>90 高、<50 通常無序", D_en:"Per-residue local confidence; >90 high, <50 usually disordered",
            ans:"D", exp:"pLDDT 是 AF 對每殘基預測準確度的估計。", exp_en:"pLDDT is AF's per-residue local accuracy estimate."},
          {type:"single", stem:"研究 IDP / 動態構象，AlphaFold 表現弱的原因？", stem_en:"AlphaFold's weakness on IDPs and dynamics?",
            A:"序列太短", A_en:"Sequences too short",
            B:"訓練集太小", B_en:"Training set too small",
            C:"IDP 本質無單一摺疊，AF 預測「最佳折疊」設定不適用", C_en:"IDPs lack single fold; AF's single-fold assumption fails",
            D:"AF 完全無法處理蛋白", D_en:"AF can't handle proteins at all",
            ans:"C", exp:"IDP 存在構象集合，需要 NMR/HDX-MS/SAXS。", exp_en:"IDPs are conformational ensembles — use NMR/HDX-MS/SAXS."},
          {type:"single", stem:"2020 年的「cryo-EM 解析度革命」達到多少解析度？", stem_en:"Cryo-EM resolution revolution (2020) reached?",
            A:"~5 Å", A_en:"~5 Å", B:"~3 Å", B_en:"~3 Å",
            C:"~1.2 Å（原子解析）", C_en:"~1.2 Å (atomic)", D:"~10 Å", D_en:"~10 Å",
            ans:"C", exp:"Yip / Nakane / Maki-Yonekura 等獨立達到 ~1.2 Å apoferritin。", exp_en:"Yip/Nakane/Maki-Yonekura independently reached ~1.2 Å on apoferritin."},
          {type:"single", stem:"X-ray 結晶學的主要限制？", stem_en:"X-ray crystallography's main limitation?",
            A:"解析度太差", A_en:"Poor resolution",
            B:"需要結晶；難結晶蛋白（如膜蛋白）困難", B_en:"Crystallization required; hard for membrane proteins",
            C:"不適合小分子", C_en:"Not for small molecules",
            D:"無法看到電子密度", D_en:"Can't see electron density",
            ans:"B", exp:"結晶是 X-ray 第一個門檻；多數膜蛋白難結晶因此 cryo-EM 取代。", exp_en:"Crystallization is the first hurdle; many membrane proteins are hard to crystallize, so cryo-EM dominates."},
          {type:"multi", stem:"哪些是 2025 結構生物學的進展？（多選）", stem_en:"Which are 2025 structural biology advances? (multi)",
            A:"AlphaFold 3", A_en:"AlphaFold 3",
            B:"微秒級 time-resolved cryo-EM", B_en:"Microsecond time-resolved cryo-EM",
            C:"Cryo-ET 細胞原位結構", C_en:"Cryo-ET in-cell structures",
            D:"Watson-Crick DNA 模型", D_en:"Watson-Crick DNA model",
            ans:["A","B","C"], exp:"D 屬於 1953，其他三項皆為近年發展。", exp_en:"D was 1953; the rest are recent."},
          {type:"multi", stem:"以下哪些工具/資料庫直接提供蛋白結構或預測？（多選）", stem_en:"Which provide protein structures or predictions? (multi)",
            A:"PDB", A_en:"PDB",
            B:"AlphaFold DB", B_en:"AlphaFold DB",
            C:"ESM Atlas", C_en:"ESM Atlas",
            D:"KEGG", D_en:"KEGG",
            ans:["A","B","C"], exp:"KEGG 是代謝路徑資料庫，非結構庫。", exp_en:"KEGG is pathway database, not structural."},
          {type:"tf", stem:"AlphaFold 3 預測模型可直接信任，無需任何驗證。", stem_en:"AF3 predictions need no validation.",
            ans:"F", exp:"必須檢查 pLDDT/PAE，且實驗仍是金標準。", exp_en:"Must check pLDDT/PAE; experiment is still gold standard."},
          {type:"tf", stem:"Cryo-ET 可在細胞原位觀察大分子結構。", stem_en:"Cryo-ET enables in-cell macromolecular structures.",
            ans:"T", exp:"FIB-SEM milling + 電子斷層可達 4-10 Å。", exp_en:"FIB-SEM milling + electron tomography achieves 4-10 Å."},
        ]
      },
      {
        id: "ch04", title: "Ch.4 醣類、脂質與生物膜", title_en: "Ch.4 Carbohydrates, Lipids & Membranes",
        block: "A", questions: [
          {type:"single", stem:"不飽和脂肪酸如何影響膜流動性？", stem_en:"Effect of unsaturated FAs on membrane fluidity?",
            A:"使膜更剛硬", A_en:"Makes membrane more rigid",
            B:"不影響流動性", B_en:"No effect",
            C:"cis 雙鍵造成扭折，增加流動性、降低 Tm", C_en:"cis double bonds kink chains — increase fluidity, lower Tm",
            D:"完全阻斷膜運輸", D_en:"Blocks transport",
            ans:"C", exp:"cis 雙鍵打斷脂質排列，使膜更流動。", exp_en:"cis double bonds disrupt packing, raising fluidity."},
          {type:"single", stem:"葡萄糖透過小腸壁進入血液主要靠？", stem_en:"Intestinal glucose absorption uses?",
            A:"簡單擴散", A_en:"Simple diffusion",
            B:"內吞作用", B_en:"Endocytosis",
            C:"SGLT1（Na⁺ 共運）→ GLUT2 出基底側", C_en:"SGLT1 (Na⁺-coupled) → GLUT2 efflux",
            D:"ATPase 直接 pump", D_en:"Direct ATPase pump",
            ans:"C", exp:"SGLT1 帶葡萄糖入腸上皮，GLUT2 從基底側出去。", exp_en:"SGLT1 imports glucose, GLUT2 exports basolaterally."},
          {type:"single", stem:"膽固醇對膜流動性的作用？", stem_en:"Cholesterol's effect on fluidity?",
            A:"永遠增加流動性", A_en:"Always increases",
            B:"流動性緩衝劑：高溫降、低溫增", B_en:"Fluidity buffer: lowers at high T, raises at low T",
            C:"永遠降低流動性", C_en:"Always decreases",
            D:"不影響", D_en:"No effect",
            ans:"B", exp:"膽固醇填補空隙也防止脂質緊密堆疊，是雙向調節劑。", exp_en:"Cholesterol fills gaps and prevents tight packing — bidirectional regulator."},
          {type:"single", stem:"PIP₂ 在訊息傳遞中的特殊角色？", stem_en:"Special role of PIP₂ in signaling?",
            A:"細胞膜結構穩定", A_en:"Membrane structure only",
            B:"水解為 IP3 + DAG（第二訊息）", B_en:"Hydrolyzed to IP3 + DAG (second messengers)",
            C:"能量儲存", C_en:"Energy storage",
            D:"光合作用", D_en:"Photosynthesis",
            ans:"B", exp:"PLC 水解 PIP₂ → IP3 (Ca²⁺ 釋放) + DAG (PKC 激活)。", exp_en:"PLC hydrolyzes PIP₂ → IP3 (releases Ca²⁺) + DAG (activates PKC)."},
          {type:"single", stem:"必需脂肪酸的特徵？", stem_en:"Characteristic of essential FAs?",
            A:"全飽和", A_en:"Fully saturated",
            B:"短鏈", B_en:"Short-chain",
            C:"人體無法合成（ω-3、ω-6）必須從食物攝取", C_en:"Cannot be synthesized by humans (ω-3, ω-6) — diet required",
            D:"動物來源", D_en:"Animal source only",
            ans:"C", exp:"人類缺乏 Δ12、Δ15 desaturase，無法引入特定位置雙鍵。", exp_en:"Humans lack Δ12 and Δ15 desaturases — must obtain ω-3/ω-6 from diet."},
          {type:"single", stem:"O₂、CO₂、類固醇激素如何過細胞膜？", stem_en:"How do O₂, CO₂, steroids cross the membrane?",
            A:"簡單擴散", A_en:"Simple diffusion",
            B:"通道蛋白", B_en:"Channel proteins",
            C:"主動運輸", C_en:"Active transport",
            D:"內吞", D_en:"Endocytosis",
            ans:"A", exp:"小且非極性分子直接擴散通過脂雙層。", exp_en:"Small nonpolar molecules diffuse directly through the bilayer."},
          {type:"multi", stem:"以下哪些是脂類？（多選）", stem_en:"Which are lipids? (multi)",
            A:"三酸甘油酯", A_en:"Triacylglycerols",
            B:"磷脂", B_en:"Phospholipids",
            C:"類固醇（如膽固醇）", C_en:"Steroids (e.g. cholesterol)",
            D:"葡萄糖", D_en:"Glucose",
            ans:["A","B","C"], exp:"葡萄糖是醣不是脂質。", exp_en:"Glucose is a sugar, not a lipid."},
          {type:"multi", stem:"哪些屬於膜運輸的「主動運輸」？（多選）", stem_en:"Which are active transport? (multi)",
            A:"Na⁺/K⁺-ATPase", A_en:"Na⁺/K⁺-ATPase",
            B:"GLUT 葡萄糖載體", B_en:"GLUT glucose transporter",
            C:"P-glycoprotein (Pgp)", C_en:"P-glycoprotein",
            D:"SGLT1 (Na⁺-coupled)", D_en:"SGLT1 (Na⁺-coupled)",
            ans:["A","C","D"], exp:"GLUT 是促進擴散，無能量。", exp_en:"GLUT is facilitated diffusion (no energy)."},
          {type:"tf", stem:"植物油在室溫下是液態，主要因為含有 cis 不飽和脂肪酸。", stem_en:"Plant oils are liquid at room T because of cis unsaturated FAs.",
            ans:"T", exp:"cis 雙鍵造成熔點降低。", exp_en:"cis double bonds lower melting point."},
          {type:"tf", stem:"抗體可以容易地穿過細胞膜進入細胞質。", stem_en:"Antibodies easily cross the cell membrane.",
            ans:"F", exp:"抗體分子大、極性高，不過細胞膜——這是為何細胞內標靶需用小分子或核酸。", exp_en:"Antibodies are large and polar — don't cross the membrane; intracellular targets need small molecules or NA."},
        ]
      },
      {
        id: "ch05", title: "Ch.5 核酸的化學與結構", title_en: "Ch.5 Nucleic Acid Chemistry & Structure",
        block: "A", questions: [
          {type:"single", stem:"為什麼 GC 富集區段熔點較高？", stem_en:"Why do GC-rich regions have higher Tm?",
            A:"GC 鹼基較重", A_en:"GC bases are heavier",
            B:"G≡C 三氫鍵 + 較強鹼基堆積", B_en:"G≡C: 3 H-bonds + stronger stacking",
            C:"與 polymerase 結合更強", C_en:"Binds DNA pol more tightly",
            D:"GC 容易斷裂", D_en:"GC is easier to break",
            ans:"B", exp:"G≡C 三氫鍵比 A=T 兩個多一個，加上更強的堆積能量。", exp_en:"G≡C uses 3 H-bonds vs A=T's 2, plus stronger stacking energy."},
          {type:"single", stem:"RNA 比 DNA 容易在鹼性條件下水解的原因？", stem_en:"Why is RNA easier to hydrolyze under base than DNA?",
            A:"RNA 鹼基較不穩定", A_en:"RNA bases less stable",
            B:"RNA 是單股", B_en:"RNA is single-stranded",
            C:"RNA 2'-OH 鄰位攻擊磷酸二酯鍵", C_en:"RNA 2'-OH attacks adjacent phosphodiester",
            D:"RNA 帶較多電荷", D_en:"RNA has more charge",
            ans:"C", exp:"2'-OH 作為親核基團攻擊鄰位磷酸，是 RNA 不穩定性的關鍵化學。", exp_en:"2'-OH performs in-line nucleophilic attack — the key chemistry of RNA instability."},
          {type:"single", stem:"mRNA 疫苗最關鍵的化學修飾？", stem_en:"Most critical chemical modification in mRNA vaccines?",
            A:"加長 polyA", A_en:"Longer polyA",
            B:"去除 5' cap", B_en:"Remove 5' cap",
            C:"換成 DNA", C_en:"Replace with DNA",
            D:"U → N1-methylpseudouridine (m1Ψ)", D_en:"U → N1-methylpseudouridine (m1Ψ)",
            ans:"D", exp:"Karikó & Weissman (2023 Nobel) 的關鍵修飾。", exp_en:"Karikó & Weissman (2023 Nobel) — the key modification."},
          {type:"single", stem:"B-DNA 每圈鹼基對？", stem_en:"Base pairs per turn of B-DNA?",
            A:"~5", A_en:"~5", B:"~10.5", B_en:"~10.5", C:"~20", C_en:"~20", D:"~30", D_en:"~30",
            ans:"B", exp:"B-DNA 約 10.5 bp/圈、A-DNA 11、Z-DNA 12。", exp_en:"B-DNA ~10.5 bp/turn; A-DNA 11; Z-DNA 12."},
          {type:"single", stem:"Cech 與 Altman 1989 Nobel 是因為發現了？", stem_en:"Cech & Altman won 1989 Nobel for?",
            A:"DNA 雙螺旋", A_en:"DNA double helix",
            B:"Ribozymes（催化 RNA）", B_en:"Ribozymes (catalytic RNA)",
            C:"PCR", C_en:"PCR",
            D:"逆轉錄酶", D_en:"Reverse transcriptase",
            ans:"B", exp:"顛覆了「酶 = 蛋白」的觀念。", exp_en:"Overturned the dogma that enzymes are only proteins."},
          {type:"single", stem:"PCR primer 設計的 3' 末端建議是？", stem_en:"PCR primer 3' end design recommendation?",
            A:"以 A、T 結尾", A_en:"End with A or T",
            B:"GC clamp（最後 2 位為 G 或 C）", B_en:"GC clamp (last 2 G or C)",
            C:"連續重複序列", C_en:"Repeat sequences",
            D:"hairpin 結構", D_en:"Hairpin structures",
            ans:"B", exp:"GC clamp 增加 3' 末端穩定性，提升擴增特異性。", exp_en:"GC clamp stabilizes 3' end for better amplification specificity."},
          {type:"multi", stem:"以下哪些是 DNA 結構特徵？（多選）", stem_en:"Which are DNA structural features? (multi)",
            A:"雙螺旋", A_en:"Double helix",
            B:"2'-去氧核糖", B_en:"2'-deoxyribose",
            C:"5'→3' 與 3'→5' 兩股反平行", C_en:"Antiparallel 5'→3' and 3'→5'",
            D:"含尿嘧啶 U", D_en:"Contains uracil U",
            ans:["A","B","C"], exp:"DNA 含 T 而非 U；U 是 RNA 的鹼基。", exp_en:"DNA has T, not U; U is in RNA."},
          {type:"multi", stem:"以下哪些是 RNA 二級結構元素？（多選）", stem_en:"Which are RNA secondary structures? (multi)",
            A:"Hairpin / stem-loop", A_en:"Hairpin / stem-loop",
            B:"Pseudoknot", B_en:"Pseudoknot",
            C:"Internal loop", C_en:"Internal loop",
            D:"α 螺旋", D_en:"α-helix",
            ans:["A","B","C"], exp:"α 螺旋是蛋白質結構，不是 RNA。", exp_en:"α-helix is a protein motif, not RNA."},
          {type:"tf", stem:"古 DNA 比古 RNA 容易保存數萬年。", stem_en:"Ancient DNA is more stable for thousands of years than ancient RNA.",
            ans:"T", exp:"DNA 缺 2'-OH，化學上更穩定。", exp_en:"DNA lacks 2'-OH and is chemically more stable."},
          {type:"tf", stem:"A=T 鹼基配對比 G≡C 鹼基配對的氫鍵多。", stem_en:"A=T base pairs use more H-bonds than G≡C.",
            ans:"F", exp:"A=T 兩個氫鍵、G≡C 三個。", exp_en:"A=T uses 2 H-bonds; G≡C uses 3."},
        ]
      },
      {
        id: "ch06", title: "Ch.6 酶催化機制", title_en: "Ch.6 Enzyme Catalytic Mechanisms",
        block: "B", questions: [
          {type:"single", stem:"絲胺酸蛋白酶的催化三聯體？", stem_en:"Serine protease catalytic triad?",
            A:"Ser-Cys-Lys", A_en:"Ser-Cys-Lys", B:"Ser-His-Asp", B_en:"Ser-His-Asp",
            C:"Tyr-Arg-Glu", C_en:"Tyr-Arg-Glu", D:"Ala-Gly-Val", D_en:"Ala-Gly-Val",
            ans:"B", exp:"chymotrypsin/trypsin/elastase 等的經典催化三聯體。", exp_en:"Classic triad of chymotrypsin/trypsin/elastase."},
          {type:"single", stem:"酶降低反應的什麼？", stem_en:"Enzymes lower what?",
            A:"ΔG", A_en:"ΔG", B:"Keq", B_en:"Keq",
            C:"活化能 Ea", C_en:"Activation energy Ea", D:"方向", D_en:"Direction",
            ans:"C", exp:"酶只改變動力學，不改熱力學。", exp_en:"Enzymes change kinetics, not thermodynamics."},
          {type:"single", stem:"最強的酶抑制劑通常是？", stem_en:"Strongest enzyme inhibitors are usually?",
            A:"基質類似物", A_en:"Substrate analogs",
            B:"產物", B_en:"Products",
            C:"鹽類", C_en:"Salts",
            D:"過渡態類似物", D_en:"Transition-state analogs",
            ans:"D", exp:"酶對 TS 的親和力遠高於基質與產物。", exp_en:"Enzymes bind TS far tighter than substrate or product."},
          {type:"single", stem:"哪種酶受 EDTA 抑制最敏感？", stem_en:"Which enzymes are most sensitive to EDTA?",
            A:"絲胺酸蛋白酶", A_en:"Serine proteases",
            B:"金屬酶（如 Zn、Mg、Mn 依賴）", B_en:"Metalloenzymes (Zn, Mg, Mn-dependent)",
            C:"半胱胺酸蛋白酶", C_en:"Cysteine proteases",
            D:"激酶", D_en:"Kinases",
            ans:"B", exp:"EDTA 螯合金屬離子，使金屬酶失活。", exp_en:"EDTA chelates metals, inactivating metalloenzymes."},
          {type:"single", stem:"2024 年「寬廣過渡態組合」觀點的核心？", stem_en:"Core of 2024 'broad TS ensemble' view?",
            A:"過渡態是單一精確結構", A_en:"TS is a single precise structure",
            B:"TS 是一群能量相似的構象（多狀態）", B_en:"TS is an ensemble of energetically similar conformations",
            C:"沒有 TS", C_en:"No TS exists",
            D:"TS 等於基質", D_en:"TS = substrate",
            ans:"B", exp:"eLife 2024：TS 為構象集合，解釋酶的演化靈活性。", exp_en:"eLife 2024: TS is an ensemble — explains evolutionary flexibility."},
          {type:"single", stem:"近接與定向效應（proximity/orientation）可貢獻多少倍速率？", stem_en:"Proximity/orientation effect contributes how much to rate?",
            A:"~2 倍", A_en:"~2×",
            B:"~10⁴–10⁸ 倍", B_en:"~10⁴–10⁸×",
            C:"~10² 倍", C_en:"~10²×",
            D:"沒有貢獻", D_en:"No contribution",
            ans:"B", exp:"光是把雙基質正確排列就能巨幅加速。", exp_en:"Properly aligning bisubstrates alone can accelerate hugely."},
          {type:"multi", stem:"以下哪些是酶催化策略？（多選）", stem_en:"Which are enzyme catalytic strategies? (multi)",
            A:"過渡態穩定化", A_en:"TS stabilization",
            B:"酸鹼催化", B_en:"Acid-base",
            C:"共價催化", C_en:"Covalent",
            D:"基質形變/誘導擬合", D_en:"Substrate distortion / induced fit",
            ans:["A","B","C","D"], exp:"四個全是經典酶催化策略。", exp_en:"All four are classic strategies."},
          {type:"multi", stem:"以下哪些酶屬於金屬酶？（多選）", stem_en:"Which are metalloenzymes? (multi)",
            A:"碳酸酐酶 (Zn²⁺)", A_en:"Carbonic anhydrase (Zn²⁺)",
            B:"超氧岐化酶 (Cu/Zn 或 Mn)", B_en:"Superoxide dismutase (Cu/Zn or Mn)",
            C:"羧肽酶 A (Zn²⁺)", C_en:"Carboxypeptidase A (Zn²⁺)",
            D:"溶菌酶 (lysozyme)", D_en:"Lysozyme",
            ans:["A","B","C"], exp:"溶菌酶不需金屬。", exp_en:"Lysozyme doesn't require metal cofactor."},
          {type:"tf", stem:"酶不會改變反應的平衡常數 Keq。", stem_en:"Enzymes don't change Keq.",
            ans:"T", exp:"酶只改變動力學，不改熱力學。", exp_en:"Enzymes change kinetics, not thermodynamics."},
          {type:"tf", stem:"DFP（二異丙基氟磷酸）是絲胺酸蛋白酶的不可逆抑制劑。", stem_en:"DFP is an irreversible inhibitor of serine proteases.",
            ans:"T", exp:"DFP 共價標記 Ser-OH，使 Ser-His-Asp 三聯體失活。", exp_en:"DFP covalently labels Ser-OH, inactivating the Ser-His-Asp triad."},
        ]
      },
      {
        id: "ch07", title: "Ch.7 酶動力學與抑制", title_en: "Ch.7 Enzyme Kinetics & Inhibition",
        block: "B", questions: [
          {type:"single", stem:"K_M 的物理意義？", stem_en:"Meaning of K_M?",
            A:"最大速率", A_en:"Max velocity",
            B:"v = V_max/2 時的 [S]，反映基質親和力", B_en:"[S] at v = V_max/2; reflects substrate affinity",
            C:"平衡常數", C_en:"Equilibrium constant",
            D:"反應級數", D_en:"Reaction order",
            ans:"B", exp:"K_M 小代表高親和力，但 K_M 也受 k1, k-1, kcat 影響。", exp_en:"Small K_M means high affinity but depends on k1, k-1, kcat."},
          {type:"single", stem:"競爭性抑制劑的 Lineweaver-Burk 特徵？", stem_en:"L-B feature of competitive inhibitor?",
            A:"同 y 截距、斜率增大", A_en:"Same y-intercept, steeper slope",
            B:"同 x 截距", B_en:"Same x-intercept",
            C:"平行線", C_en:"Parallel lines",
            D:"通過原點", D_en:"Pass through origin",
            ans:"A", exp:"V_max 不變、K_M 表觀增加，所以 y 截距 (1/V_max) 不變、斜率變大。", exp_en:"V_max unchanged, apparent K_M increases → y-int unchanged, slope steeper."},
          {type:"single", stem:"k_cat/K_M ≈ 10⁹ M⁻¹s⁻¹ 表示？", stem_en:"k_cat/K_M ≈ 10⁹ M⁻¹s⁻¹ means?",
            A:"酶太慢", A_en:"Slow enzyme",
            B:"結構不穩定", B_en:"Unstable",
            C:"接近擴散極限——「完美酶」", C_en:"Near diffusion limit — 'catalytic perfection'",
            D:"V_max 很大", D_en:"Large V_max",
            ans:"C", exp:"catalase, carbonic anhydrase 等屬於這一類。", exp_en:"Catalase, carbonic anhydrase belong to this class."},
          {type:"single", stem:"不競爭性抑制（uncompetitive）的特徵？", stem_en:"Uncompetitive inhibition character?",
            A:"V_max 不變，K_M 增加", A_en:"V_max unchanged, K_M increases",
            B:"V_max 與 K_M 都減小（抑制劑只結合 ES）", B_en:"Both V_max and K_M decrease (binds ES only)",
            C:"V_max 減小、K_M 不變", C_en:"V_max decreases, K_M unchanged",
            D:"無變化", D_en:"No change",
            ans:"B", exp:"不競爭抑制劑專結合 ES 複合物 → 兩個動力學參數同向下降。", exp_en:"Uncompetitive binds only ES — both parameters decrease."},
          {type:"single", stem:"阿斯匹靈的化學作用機制？", stem_en:"Aspirin's mechanism?",
            A:"競爭性可逆抑制", A_en:"Reversible competitive",
            B:"不可逆共價乙醯化 COX 的 Ser", B_en:"Irreversible covalent acetylation of COX's Ser",
            C:"變構激活", C_en:"Allosteric activation",
            D:"DNA 結合", D_en:"DNA binding",
            ans:"B", exp:"阿斯匹靈將 COX-1/2 Ser529/516 乙醯化，永久失活。", exp_en:"Aspirin acetylates COX-1/2 Ser529/516 — permanently inactivated."},
          {type:"single", stem:"Michaelis-Menten 假設的核心？", stem_en:"Core MM assumptions?",
            A:"基質與酶比例 1:1", A_en:"E:S = 1:1",
            B:"ES 處於穩態 + [S] ≫ [E]", B_en:"ES at steady-state + [S] ≫ [E]",
            C:"溫度不影響", C_en:"T-independent",
            D:"pH 不影響", D_en:"pH-independent",
            ans:"B", exp:"Briggs-Haldane 1925 穩態假設，加上基質遠多於酶。", exp_en:"Briggs-Haldane 1925 steady-state assumption + substrate excess."},
          {type:"multi", stem:"以下哪些是 statins 類藥物的特徵？（多選）", stem_en:"Which describe statin drugs? (multi)",
            A:"競爭性 HMG-CoA 還原酶抑制劑", A_en:"Competitive HMG-CoA reductase inhibitor",
            B:"過渡態類似物", B_en:"TS analog",
            C:"降低 LDL 膽固醇", C_en:"Lower LDL cholesterol",
            D:"激活脂肪酸合成", D_en:"Activate FA synthesis",
            ans:["A","B","C"], exp:"statins 是抑制劑（非激活），且結構類似 mevalonate TS。", exp_en:"Statins inhibit (not activate) and resemble the mevalonate TS."},
          {type:"multi", stem:"以下何者會降低 V_max？（多選）", stem_en:"Which reduce V_max? (multi)",
            A:"非競爭性抑制劑", A_en:"Non-competitive inhibitor",
            B:"不競爭性抑制劑", B_en:"Uncompetitive inhibitor",
            C:"競爭性抑制劑", C_en:"Competitive inhibitor",
            D:"混合型抑制劑", D_en:"Mixed inhibitor",
            ans:["A","B","D"], exp:"競爭性 V_max 不變；其他都降。", exp_en:"Competitive doesn't change V_max; others do."},
          {type:"tf", stem:"競爭性抑制可以用提高 [S] 來克服。", stem_en:"Competitive inhibition can be overcome by raising [S].",
            ans:"T", exp:"V_max 不變，所以足夠高的 [S] 能達到原來的 V_max。", exp_en:"V_max unchanged — sufficient [S] reaches original V_max."},
          {type:"tf", stem:"IC50 等於 K_i。", stem_en:"IC50 equals K_i.",
            ans:"F", exp:"IC50 與 K_i 有關但不相等；對競爭性抑制 IC50 = K_i (1 + [S]/K_M)。", exp_en:"IC50 ≠ K_i; for competitive: IC50 = K_i (1 + [S]/K_M)."},
        ]
      },
      {
        id: "ch08", title: "Ch.8 酶調控", title_en: "Ch.8 Enzyme Regulation",
        block: "B", questions: [
          {type:"single", stem:"Hill 係數 = 2.8 代表？", stem_en:"Hill coefficient 2.8 means?",
            A:"反應級數 2.8", A_en:"Reaction order 2.8",
            B:"無協同", B_en:"No cooperativity",
            C:"強正向協同（如血紅蛋白）", C_en:"Strong positive cooperativity (like Hb)",
            D:"競爭性抑制", D_en:"Competitive inhibition",
            ans:"C", exp:"Hill > 1 為正協同；血紅蛋白 ≈ 2.8。", exp_en:"Hill > 1 = positive coop; hemoglobin ≈ 2.8."},
          {type:"single", stem:"凝血酶原激活方式？", stem_en:"How is prothrombin activated?",
            A:"磷酸化", A_en:"Phosphorylation",
            B:"蛋白酶切割（不可逆酶原激活）", B_en:"Proteolytic cleavage (irreversible)",
            C:"變構", C_en:"Allosteric",
            D:"轉錄誘導", D_en:"Transcriptional",
            ans:"B", exp:"凝血酶原 → 凝血酶為單向不可逆切割。", exp_en:"Prothrombin → thrombin is one-way proteolytic activation."},
          {type:"single", stem:"磷酸化為何適合短期可逆訊息？", stem_en:"Why phosphorylation for short reversible signaling?",
            A:"消耗大量能量", A_en:"Costs lots of energy",
            B:"不可逆", B_en:"Irreversible",
            C:"1 ATP 即可、可秒級逆轉，且 −2 電荷被 SH2/14-3-3 識別", C_en:"1 ATP, sec-scale reversal, −2 charge read by SH2/14-3-3",
            D:"永久改變蛋白", D_en:"Permanent change",
            ans:"C", exp:"磷酸化是「最佳的細胞訊息開關」。", exp_en:"Phosphorylation is the optimal cellular signaling switch."},
          {type:"single", stem:"MWC 與 KNF 變構模型的核心差別？", stem_en:"MWC vs KNF core difference?",
            A:"MWC 完全對稱協同切換；KNF 依序誘導，可不對稱", A_en:"MWC: symmetric concerted; KNF: sequential, asymmetric",
            B:"完全相同", B_en:"Same",
            C:"MWC 由 Koshland 提出", C_en:"MWC was proposed by Koshland",
            D:"KNF 不存在", D_en:"KNF doesn't exist",
            ans:"A", exp:"MWC (Monod-Wyman-Changeux 1965) vs KNF (Koshland-Némethy-Filmer 1966)。", exp_en:"MWC (Monod 1965) vs KNF (Koshland 1966)."},
          {type:"single", stem:"PFK-1 最強的變構激活劑是？", stem_en:"Strongest allosteric activator of PFK-1?",
            A:"ATP", A_en:"ATP",
            B:"citrate", B_en:"citrate",
            C:"F2,6BP（由 PFK-2 合成）", C_en:"F2,6BP (made by PFK-2)",
            D:"NAD⁺", D_en:"NAD⁺",
            ans:"C", exp:"F2,6BP 是糖解最強激活劑，回應胰島素。", exp_en:"F2,6BP is the strongest activator, responsive to insulin."},
          {type:"single", stem:"人類基因組編碼多少個 kinases？", stem_en:"Human genome encodes how many kinases?",
            A:"~50", A_en:"~50", B:"~518（kinome）", B_en:"~518 (kinome)",
            C:"~5000", C_en:"~5000", D:"~10", D_en:"~10",
            ans:"B", exp:"Manning 2002 Science 文章：人類 kinome ~518 個。", exp_en:"Manning 2002 Science: ~518 kinases."},
          {type:"multi", stem:"哪些是常見的翻譯後修飾？（多選）", stem_en:"Which are common PTMs? (multi)",
            A:"磷酸化", A_en:"Phosphorylation",
            B:"乙醯化", B_en:"Acetylation",
            C:"泛素化", C_en:"Ubiquitination",
            D:"DNA 複製", D_en:"DNA replication",
            ans:["A","B","C"], exp:"DNA 複製不是 PTM。", exp_en:"DNA replication is not a PTM."},
          {type:"multi", stem:"以下哪些屬於變構效應？（多選）", stem_en:"Which are allosteric effects? (multi)",
            A:"氧結合血紅蛋白引發其他次單元構象變", A_en:"O₂ binding hemoglobin induces other subunits",
            B:"F2,6BP 結合 PFK-1 激活", B_en:"F2,6BP binds PFK-1 to activate",
            C:"ATP 抑制 PFK-1", C_en:"ATP inhibits PFK-1",
            D:"蛋白變性", D_en:"Protein denaturation",
            ans:["A","B","C"], exp:"蛋白變性不是變構調節。", exp_en:"Denaturation is not allosteric regulation."},
          {type:"tf", stem:"變構酶的動力學曲線通常呈 S 形而非雙曲線。", stem_en:"Allosteric enzymes show sigmoidal kinetics, not hyperbolic.",
            ans:"T", exp:"協同性產生 S 形曲線。", exp_en:"Cooperativity produces sigmoidal curves."},
          {type:"tf", stem:"血紅蛋白與肌紅蛋白都呈現協同性。", stem_en:"Both hemoglobin and myoglobin show cooperativity.",
            ans:"F", exp:"血紅蛋白 (α₂β₂) 有協同；肌紅蛋白 (單聚體) 無。", exp_en:"Hemoglobin (α₂β₂) is cooperative; myoglobin (monomer) is not."},
        ]
      },
      {
        id: "ch09", title: "Ch.9 生物能量學", title_en: "Ch.9 Bioenergetics",
        block: "C", questions: [
          {type:"single", stem:"ATP 適合做能量貨幣的原因？", stem_en:"Why ATP suits as energy currency?",
            A:"是能量最高的化合物", A_en:"Highest energy",
            B:"化學鍵極強", B_en:"Especially strong bond",
            C:"能量中等——可接受高能磷酸、又能轉移給低能受體", C_en:"Intermediate energy — accepts from high-E donors, donates to low-E acceptors",
            D:"不會水解", D_en:"Doesn't hydrolyze",
            ans:"C", exp:"PEP > 1,3-BPG > ATP > G6P > glycerol-3-P。", exp_en:"PEP > 1,3-BPG > ATP > G6P > glycerol-3-P."},
          {type:"single", stem:"NADH → O₂（n=2, ΔE°'=1.14 V）的 ΔG°'？", stem_en:"ΔG°' for NADH → O₂?",
            A:"−30 kJ/mol", A_en:"−30 kJ/mol",
            B:"−220 kJ/mol", B_en:"−220 kJ/mol",
            C:"+220 kJ/mol", C_en:"+220 kJ/mol",
            D:"0", D_en:"0",
            ans:"B", exp:"ΔG°' = −n·F·ΔE°' = −2 × 96.485 × 1.14 ≈ −220。", exp_en:"ΔG°' = −n·F·ΔE°' = −2 × 96.485 × 1.14 ≈ −220."},
          {type:"single", stem:"NADPH 與 NADH 的分工？", stem_en:"NADPH vs NADH division of labor?",
            A:"相同", A_en:"Same",
            B:"NADH 合成、NADPH 分解", B_en:"NADH for synthesis; NADPH for catabolism",
            C:"NADH 分解產 ATP；NADPH 合成代謝 + 抗氧化", C_en:"NADH for catabolism/ATP; NADPH for biosynthesis & antioxidant",
            D:"NADPH 不存在", D_en:"NADPH doesn't exist",
            ans:"C", exp:"細胞用兩個獨立池維持分工。", exp_en:"Cell maintains separate pools for the two functions."},
          {type:"single", stem:"能量電荷 (EC) 健康值範圍？", stem_en:"Healthy energy charge range?",
            A:"0.0–0.3", A_en:"0.0–0.3", B:"0.4–0.5", B_en:"0.4–0.5",
            C:"0.85–0.95", C_en:"0.85–0.95", D:"1.0+", D_en:"1.0+",
            ans:"C", exp:"健康細胞 EC ≈ 0.85–0.95；< 0.5 觸發 apoptosis。", exp_en:"Healthy cells EC ≈ 0.85–0.95; < 0.5 triggers apoptosis."},
          {type:"single", stem:"標準 ΔG°' 與細胞內 ΔG 為何常常不同？", stem_en:"Why does standard ΔG°' differ from cellular ΔG?",
            A:"標準狀態 1 M 與細胞內濃度差很多", A_en:"1 M standard differs from real cellular concentrations",
            B:"標準是測量錯誤", B_en:"Standard is wrong",
            C:"細胞用其他單位", C_en:"Cells use different units",
            D:"完全相同", D_en:"They're identical",
            ans:"A", exp:"細胞內 ATP/ADP ~100，使實際 ΔG 較標準負許多。", exp_en:"Cellular ATP/ADP ~100 makes ΔG much more negative than standard."},
          {type:"single", stem:"以下哪一個化合物的水解 ΔG°' 最負？", stem_en:"Which has most negative ΔG°' of hydrolysis?",
            A:"PEP (-61.9)", A_en:"PEP (-61.9)",
            B:"ATP (-30.5)", B_en:"ATP (-30.5)",
            C:"G6P (-13.8)", C_en:"G6P (-13.8)",
            D:"Pyrophosphate (-19)", D_en:"Pyrophosphate (-19)",
            ans:"A", exp:"PEP 是糖解的最後一步：將其磷酸轉到 ADP 產生 ATP。", exp_en:"PEP is glycolysis' last step: transfers P to ADP, making ATP."},
          {type:"multi", stem:"以下哪些是高能磷酸化合物（ΔG°' < -30）？（多選）", stem_en:"Which are high-energy phosphates? (multi)",
            A:"PEP", A_en:"PEP",
            B:"1,3-bisphosphoglycerate", B_en:"1,3-BPG",
            C:"phosphocreatine", C_en:"Phosphocreatine",
            D:"G6P", D_en:"G6P",
            ans:["A","B","C"], exp:"G6P 是低能磷酸化合物（-13.8）。", exp_en:"G6P is low-energy (-13.8)."},
          {type:"multi", stem:"能量偶合策略包括？（多選）", stem_en:"Energy coupling strategies include? (multi)",
            A:"ATP 水解", A_en:"ATP hydrolysis",
            B:"離子梯度（如 H⁺、Na⁺）", B_en:"Ion gradients (H⁺, Na⁺)",
            C:"PEP 高能化合物", C_en:"High-energy compounds like PEP",
            D:"光合作用直接做合成", D_en:"Direct photosynthesis to synthesis",
            ans:["A","B","C"], exp:"光合也需透過 ATP/NADPH 中介，不是直接。", exp_en:"Photosynthesis still uses ATP/NADPH intermediates."},
          {type:"tf", stem:"酶能改變反應的方向。", stem_en:"Enzymes can reverse reaction direction.",
            ans:"F", exp:"方向由熱力學決定，酶只能加速。", exp_en:"Thermodynamics sets direction; enzymes only speed it up."},
          {type:"tf", stem:"細胞內 ATP 水解的 ΔG 比標準狀態下更負。", stem_en:"Cellular ATP ΔG is more negative than standard.",
            ans:"T", exp:"高 ATP/ADP 比例使 ΔG ≈ -50 至 -65 kJ/mol。", exp_en:"High ATP/ADP ratio makes ΔG ≈ -50 to -65 kJ/mol."},
        ]
      },
      {
        id: "ch10", title: "Ch.10 醣類代謝", title_en: "Ch.10 Carbohydrate Metabolism",
        block: "C", questions: [
          {type:"single", stem:"糖解淨產出？", stem_en:"Net glycolysis yield per glucose?",
            A:"4 ATP + 4 NADH", A_en:"4 ATP + 4 NADH",
            B:"2 ATP + 2 NADH + 2 丙酮酸", B_en:"2 ATP + 2 NADH + 2 pyruvate",
            C:"30 ATP", C_en:"30 ATP",
            D:"2 FADH₂ + 1 ATP", D_en:"2 FADH₂ + 1 ATP",
            ans:"B", exp:"投資 2 ATP，收割 4 ATP，淨 2。", exp_en:"Invest 2 ATP, gain 4, net 2."},
          {type:"single", stem:"糖解最重要的調控酶？", stem_en:"Master regulator of glycolysis?",
            A:"己糖激酶", A_en:"Hexokinase",
            B:"丙酮酸激酶", B_en:"Pyruvate kinase",
            C:"PFK-1（F2,6BP/AMP/ATP/citrate 多重調控）", C_en:"PFK-1 (F2,6BP/AMP/ATP/citrate)",
            D:"Aldolase", D_en:"Aldolase",
            ans:"C", exp:"PFK-1 是糖解最重要的不可逆調控節點。", exp_en:"PFK-1 is the master irreversible regulatory step."},
          {type:"single", stem:"Warburg 效應的最佳解釋？", stem_en:"Best explanation for Warburg effect?",
            A:"癌細胞缺粒線體", A_en:"Cancer cells lack mitochondria",
            B:"ATP 不足", B_en:"ATP shortage",
            C:"快速分裂需要 PPP/糖解分支供應合成代謝前體", C_en:"Rapid division needs PPP/glycolysis biosynthetic intermediates",
            D:"隨機", D_en:"Random",
            ans:"C", exp:"Vander Heiden 2009 Science 經典解釋：物料 + 微環境。", exp_en:"Vander Heiden 2009: biosynthetic intermediates + microenvironment."},
          {type:"single", stem:"G6PD 缺陷的關鍵後果？", stem_en:"Key consequence of G6PD deficiency?",
            A:"葡萄糖無法吸收", A_en:"Can't absorb glucose",
            B:"NADPH 不足 → 紅血球無法重生 glutathione → 氧化壓力溶血（蠶豆症）", B_en:"NADPH ↓ → can't regenerate glutathione → RBC oxidative hemolysis (favism)",
            C:"高血糖", C_en:"Hyperglycemia",
            D:"低血糖", D_en:"Hypoglycemia",
            ans:"B", exp:"G6PD 是 PPP 的限速酶；缺陷時 NADPH 供應不足。", exp_en:"G6PD is the rate-limiting PPP enzyme; deficiency depletes NADPH."},
          {type:"single", stem:"糖質新生為什麼不能用糖解反向？", stem_en:"Why isn't gluconeogenesis simply reverse glycolysis?",
            A:"沒有 PEP", A_en:"No PEP",
            B:"糖解三個不可逆步驟需要繞道（PC+PEPCK、FBPase、G6Pase）", B_en:"3 irreversible glycolysis steps need bypasses (PC+PEPCK, FBPase, G6Pase)",
            C:"細胞質沒有酶", C_en:"No cytoplasmic enzymes",
            D:"完全可以反向", D_en:"It actually can",
            ans:"B", exp:"不可逆熱力學需要不同酶才能繞回。", exp_en:"Irreversible thermodynamics requires bypass enzymes."},
          {type:"single", stem:"PPP 氧化階段產生什麼？", stem_en:"PPP oxidative phase produces?",
            A:"ATP", A_en:"ATP",
            B:"NADH + CO₂", B_en:"NADH + CO₂",
            C:"2 NADPH + CO₂", C_en:"2 NADPH + CO₂",
            D:"丙酮酸", D_en:"Pyruvate",
            ans:"C", exp:"每葡萄糖 6-P 在 PPP 氧化階段產 2 NADPH 與 1 CO₂。", exp_en:"Each G6P yields 2 NADPH + 1 CO₂ in oxidative PPP."},
          {type:"multi", stem:"糖解的三個不可逆步驟是？（多選）", stem_en:"Three irreversible glycolysis steps? (multi)",
            A:"己糖激酶（Step 1）", A_en:"Hexokinase (step 1)",
            B:"PFK-1（Step 3）", B_en:"PFK-1 (step 3)",
            C:"丙酮酸激酶（Step 10）", C_en:"Pyruvate kinase (step 10)",
            D:"Aldolase（Step 4）", D_en:"Aldolase (step 4)",
            ans:["A","B","C"], exp:"這三個是糖質新生需要繞道的位置。", exp_en:"These three are the bypasses needed for gluconeogenesis."},
          {type:"multi", stem:"哪些細胞缺乏 G6Pase 故無法輸出葡萄糖到血液？（多選）", stem_en:"Which cells lack G6Pase and can't export glucose? (multi)",
            A:"骨骼肌", A_en:"Skeletal muscle",
            B:"肝臟", B_en:"Liver",
            C:"腦", C_en:"Brain",
            D:"紅血球", D_en:"RBCs",
            ans:["A","C","D"], exp:"只有肝與腎有 G6Pase，可輸出葡萄糖。", exp_en:"Only liver and kidney have G6Pase to export glucose."},
          {type:"tf", stem:"肝糖（glycogen）合成只發生在肝臟。", stem_en:"Glycogen synthesis only happens in liver.",
            ans:"F", exp:"骨骼肌也大量儲存肝糖，但只供自用。", exp_en:"Muscle stores glycogen too, for its own use only."},
          {type:"tf", stem:"Metformin 主要透過抑制肝糖質新生治療糖尿病。", stem_en:"Metformin primarily treats diabetes by inhibiting hepatic gluconeogenesis.",
            ans:"T", exp:"AMPK 激活 + mGPD/GDH 抑制。", exp_en:"AMPK activation + mGPD/GDH inhibition."},
        ]
      },
      {
        id: "ch11", title: "Ch.11 TCA 循環與氧化磷酸化", title_en: "Ch.11 TCA & OxPhos",
        block: "C", questions: [
          {type:"single", stem:"每葡萄糖完全氧化淨產 ATP（2000 後修訂值）？", stem_en:"Net ATP per glucose (post-2000 revision)?",
            A:"2", A_en:"2", B:"4", B_en:"4", C:"38", C_en:"38",
            D:"~30–32", D_en:"~30–32",
            ans:"D", exp:"P/O 修訂：NADH 2.5, FADH₂ 1.5。", exp_en:"Revised P/O: NADH 2.5, FADH₂ 1.5."},
          {type:"single", stem:"Mitchell 化學滲透學說的核心？", stem_en:"Core of Mitchell's chemiosmotic theory?",
            A:"ETC 直接形成高能鍵", A_en:"ETC forms high-energy bond directly",
            B:"NADH 直接磷酸化 ADP", B_en:"NADH directly phosphorylates ADP",
            C:"ETC 建立質子梯度，ATP synthase 利用之", C_en:"ETC builds H⁺ gradient; ATP synthase uses it",
            D:"質子不參與", D_en:"Protons don't participate",
            ans:"C", exp:"Mitchell 1961, 1978 Nobel。", exp_en:"Mitchell 1961, 1978 Nobel."},
          {type:"single", stem:"DNP 的代謝效果？", stem_en:"Effect of DNP?",
            A:"抑制 PDH", A_en:"Inhibits PDH",
            B:"增加 ATP", B_en:"Increases ATP",
            C:"阻斷 TCA", C_en:"Blocks TCA",
            D:"解偶聯：H⁺ 漏回基質，能量變熱、ATP 急降", D_en:"Uncoupler: H⁺ leaks back, energy → heat, ATP drops",
            ans:"D", exp:"DNP 是經典解偶聯劑，曾用減重已禁。", exp_en:"DNP is classic uncoupler, banned for diet use due to lethal hyperthermia."},
          {type:"single", stem:"哪個 ETC 複合體不泵 H⁺？", stem_en:"Which ETC complex doesn't pump H⁺?",
            A:"Complex I", A_en:"Complex I",
            B:"Complex II（Succinate DH）", B_en:"Complex II (Succinate DH)",
            C:"Complex III", C_en:"Complex III",
            D:"Complex IV", D_en:"Complex IV",
            ans:"B", exp:"Complex II 僅是 FADH₂ 入口，不泵 H⁺。", exp_en:"Complex II is only the FADH₂ entry, no H⁺ pumping."},
          {type:"single", stem:"Cyanide (CN⁻) 的中毒機制？", stem_en:"Cyanide poisoning mechanism?",
            A:"抑 Complex I", A_en:"Inhibits Complex I",
            B:"抑 Complex II", B_en:"Inhibits Complex II",
            C:"抑 Complex III", C_en:"Inhibits Complex III",
            D:"抑 Complex IV（cytochrome c oxidase）", D_en:"Inhibits Complex IV (cytochrome c oxidase)",
            ans:"D", exp:"CN⁻ 結合 Fe³⁺ 於 cytochrome a3，阻 O₂ 還原。", exp_en:"CN⁻ binds Fe³⁺ in cytochrome a3, blocking O₂ reduction."},
          {type:"single", stem:"UCP1 在棕色脂肪的功能？", stem_en:"Function of UCP1 in brown fat?",
            A:"合成 ATP", A_en:"Synthesize ATP",
            B:"質子漏 → 能量變熱（產熱）", B_en:"Proton leak → energy as heat (thermogenesis)",
            C:"脂肪合成", C_en:"FA synthesis",
            D:"訊息傳遞", D_en:"Signaling",
            ans:"B", exp:"UCP1 允許 H⁺ 漏回基質，能量直接變熱。", exp_en:"UCP1 lets H⁺ leak back, dissipating energy as heat."},
          {type:"multi", stem:"哪些屬於 TCA 循環的產物（每圈）？（多選）", stem_en:"Per-cycle TCA products? (multi)",
            A:"3 NADH", A_en:"3 NADH",
            B:"1 FADH₂", B_en:"1 FADH₂",
            C:"1 GTP", C_en:"1 GTP",
            D:"4 ATP", D_en:"4 ATP",
            ans:["A","B","C"], exp:"TCA 不直接產 ATP，僅 1 GTP 受質磷酸化。", exp_en:"TCA makes 1 GTP via substrate-level, not ATP directly."},
          {type:"multi", stem:"哪些情境會產生乳酸性酸中毒？（多選）", stem_en:"Which cause lactic acidosis? (multi)",
            A:"缺氧（休克）", A_en:"Hypoxia (shock)",
            B:"粒線體疾病", B_en:"Mitochondrial disease",
            C:"Metformin（高劑量）", C_en:"Metformin (high dose)",
            D:"喝水", D_en:"Drinking water",
            ans:["A","B","C"], exp:"前三者都會抑制氧化磷酸化或迫使糖解。", exp_en:"All three impair OXPHOS or force glycolysis."},
          {type:"tf", stem:"PDH 是丙酮酸進入 TCA 的入口酶，且為不可逆。", stem_en:"PDH is the irreversible entry enzyme for pyruvate into TCA.",
            ans:"T", exp:"PDH 脫羧不可逆，連結糖解到 TCA。", exp_en:"PDH irreversibly decarboxylates pyruvate, linking glycolysis to TCA."},
          {type:"tf", stem:"TCA 循環只進行氧化代謝，不提供合成材料。", stem_en:"TCA only does oxidation; no biosynthesis.",
            ans:"F", exp:"TCA 是「代謝中央車站」，中間體可被抽出做合成。", exp_en:"TCA is the metabolic hub — intermediates are siphoned for biosynthesis."},
        ]
      },
      {
        id: "ch12", title: "Ch.12 脂質與胺基酸代謝", title_en: "Ch.12 Lipid & AA Metabolism",
        block: "C", questions: [
          {type:"single", stem:"為什麼 β 氧化在粒線體，FA 合成在細胞質？", stem_en:"Why β-oxidation in mito but FA synthesis in cytosol?",
            A:"美觀", A_en:"Aesthetic",
            B:"巧合", B_en:"Coincidence",
            C:"區隔避免無效循環，且用不同還原力 (NADH/FAD vs NADPH)", C_en:"Compartmentalized to avoid futile cycles; different reducing power",
            D:"位置相同", D_en:"Same location",
            ans:"C", exp:"分離且用不同還原力池確保不會同時跑。", exp_en:"Separation and different reducing pools prevent simultaneous flux."},
          {type:"single", stem:"DKA（糖尿病酮酸中毒）根本原因？", stem_en:"Root cause of DKA?",
            A:"過度進食", A_en:"Overeating",
            B:"胰島素缺乏 → 脂解失控 → 酮體過剩 → 酸中毒", B_en:"Insulin deficiency → uncontrolled lipolysis → ketone excess → acidosis",
            C:"缺水", C_en:"Dehydration",
            D:"高鉀", D_en:"Hyperkalemia",
            ans:"B", exp:"T1DM 急症，胰島素絕對不足。", exp_en:"T1DM emergency — absolute insulin deficiency."},
          {type:"single", stem:"OTC 缺陷的特徵？", stem_en:"Features of OTC deficiency?",
            A:"自體隱性", A_en:"Autosomal recessive",
            B:"不影響血氨", B_en:"No ammonia effect",
            C:"X 連鎖、最常見尿素循環缺陷、瓜胺酸↓、血氨↑↑", C_en:"X-linked, most common UCD, citrulline↓, ammonia↑↑",
            D:"影響糖解", D_en:"Affects glycolysis",
            ans:"C", exp:"OTC X 連鎖最常見，男性嚴重。", exp_en:"OTC is X-linked, most common; males most severely affected."},
          {type:"single", stem:"棕櫚酸（C16）完全氧化 ATP 產量？", stem_en:"Palmitate (C16) full oxidation ATP yield?",
            A:"~30", A_en:"~30", B:"~50", B_en:"~50",
            C:"~106", C_en:"~106", D:"~200", D_en:"~200",
            ans:"C", exp:"7 輪 β 氧化 + 8 acetyl-CoA → 各 10 ATP → 共 ~106。", exp_en:"7 β-oxidation rounds + 8 acetyl-CoA × 10 ATP = ~106."},
          {type:"single", stem:"Malonyl-CoA 的雙重角色？", stem_en:"Malonyl-CoA's dual role?",
            A:"是脂解的中間體", A_en:"Intermediate of lipolysis",
            B:"FA 合成第一中間體 + 抑制 CPT-1（阻 FA 入粒線體燃燒）", B_en:"First intermediate of FA synthesis + inhibits CPT-1 (blocks FA entry to mito)",
            C:"DNA 合成原料", C_en:"DNA precursor",
            D:"訊息分子", D_en:"Signaling molecule",
            ans:"B", exp:"是脂合 vs 脂解的關鍵切換開關。", exp_en:"The master switch between lipogenesis and lipolysis."},
          {type:"single", stem:"哪些胺基酸是「純酮原性」？", stem_en:"Which AAs are purely ketogenic?",
            A:"Lys 與 Leu", A_en:"Lys and Leu",
            B:"Ala 與 Gly", B_en:"Ala and Gly",
            C:"Glu 與 Asp", C_en:"Glu and Asp",
            D:"Ser 與 Thr", D_en:"Ser and Thr",
            ans:"A", exp:"Lys 與 Leu 完全不進入糖質新生。", exp_en:"Lys and Leu cannot enter gluconeogenesis."},
          {type:"multi", stem:"哪些是尿素循環缺陷的常見症狀？（多選）", stem_en:"Common symptoms of urea cycle defects? (multi)",
            A:"高血氨", A_en:"Hyperammonemia",
            B:"嗜睡 / 抽搐", B_en:"Lethargy / seizures",
            C:"昏迷", C_en:"Coma",
            D:"低血糖", D_en:"Hypoglycemia",
            ans:["A","B","C"], exp:"高血氨直接神經毒；不一定低血糖。", exp_en:"Hyperammonemia is direct neurotoxin; hypoglycemia is not specific."},
          {type:"multi", stem:"哪些屬於酮體？（多選）", stem_en:"Which are ketone bodies? (multi)",
            A:"β-羥丁酸", A_en:"β-hydroxybutyrate",
            B:"乙醯乙酸", B_en:"Acetoacetate",
            C:"丙酮", C_en:"Acetone",
            D:"乙醯-CoA", D_en:"Acetyl-CoA",
            ans:["A","B","C"], exp:"Acetyl-CoA 是酮體前體，非酮體本身。", exp_en:"Acetyl-CoA is the precursor, not a ketone body itself."},
          {type:"tf", stem:"大腦在飢餓時可主要使用酮體作為能源。", stem_en:"During starvation, brain can use ketones as primary fuel.",
            ans:"T", exp:"長期飢餓酮體可佔大腦 75% 能源。", exp_en:"During prolonged starvation, ketones can supply 75% of brain energy."},
          {type:"tf", stem:"轉胺反應的輔因子是 vitamin B6 衍生物 PLP。", stem_en:"Transamination uses vitamin B6 (PLP) cofactor.",
            ans:"T", exp:"PLP 為 ALT、AST 等的輔因子；B6 缺乏影響此酶。", exp_en:"PLP is cofactor for ALT, AST; B6 deficiency impairs them."},
        ]
      },
      {
        id: "ch13", title: "Ch.13 代謝整合與荷爾蒙調控", title_en: "Ch.13 Integration & Hormonal Control",
        block: "C", questions: [
          {type:"single", stem:"F2,6BP 的角色？", stem_en:"Role of F2,6BP?",
            A:"糖解中間", A_en:"Glycolysis intermediate",
            B:"蛋白合成原料", B_en:"Protein synthesis substrate",
            C:"變構訊號：胰島素↑F2,6BP→糖解；升糖素↓F2,6BP→糖質新生", C_en:"Allosteric signal: insulin↑→glycolysis; glucagon↓→gluconeogenesis",
            D:"無作用", D_en:"No role",
            ans:"C", exp:"由 PFK-2/FBPase-2 雙功能酶調節。", exp_en:"Regulated by bifunctional PFK-2/FBPase-2."},
          {type:"single", stem:"Metformin 主要治糖尿病機制？", stem_en:"Main mechanism of metformin?",
            A:"刺激胰島素分泌", A_en:"Stimulates insulin secretion",
            B:"激活 AMPK + 抑制 mGPD/GDH → 抑制肝糖質新生", B_en:"Activates AMPK + inhibits mGPD/GDH → suppresses hepatic gluconeogenesis",
            C:"抑脂吸收", C_en:"Inhibits fat absorption",
            D:"增加食慾", D_en:"Increases appetite",
            ans:"B", exp:"T2DM 一線藥；AMPK + mitochondrial 雙重靶。", exp_en:"First-line T2DM drug; dual AMPK + mitochondrial target."},
          {type:"single", stem:"紅血球為什麼是「絕對乳酸生產者」？", stem_en:"Why RBCs are obligate lactate producers?",
            A:"缺糖", A_en:"No glucose",
            B:"無粒線體，只能糖解 → 乳酸 (再生 NAD⁺)", B_en:"No mitochondria — glycolysis only, → lactate (regenerates NAD⁺)",
            C:"大腦命令", C_en:"Brain command",
            D:"缺酶", D_en:"Missing enzymes",
            ans:"B", exp:"RBC 成熟時失去粒線體。", exp_en:"Mature RBCs lose mitochondria."},
          {type:"single", stem:"大腦的能源限制？", stem_en:"Brain's fuel limitation?",
            A:"只能燒酮體", A_en:"Only ketones",
            B:"可使用脂肪酸", B_en:"Can use FAs",
            C:"主要葡萄糖（飢餓時 75% 酮體），絕不燒脂肪酸", C_en:"Mainly glucose; in starvation 75% ketones; never FAs",
            D:"只能燒胺基酸", D_en:"Only AAs",
            ans:"C", exp:"脂肪酸不過血腦屏障。", exp_en:"FAs don't cross BBB."},
          {type:"single", stem:"AMPK 何時被激活？", stem_en:"When is AMPK activated?",
            A:"進食後 ATP 高時", A_en:"After meal when ATP is high",
            B:"AMP/ATP 比例↑（能量低）", B_en:"AMP/ATP ratio rises (low energy)",
            C:"無關能量", C_en:"Independent of energy",
            D:"睡眠時", D_en:"During sleep only",
            ans:"B", exp:"AMPK 是細胞「能量電量計」，AMP↑時激活。", exp_en:"AMPK is the cell's fuel gauge — active when AMP↑."},
          {type:"single", stem:"心臟最偏好的能源？", stem_en:"Heart's preferred fuel?",
            A:"葡萄糖", A_en:"Glucose",
            B:"脂肪酸（~70%）", B_en:"Fatty acids (~70%)",
            C:"乳酸", C_en:"Lactate",
            D:"胺基酸", D_en:"Amino acids",
            ans:"B", exp:"心肌偏脂肪酸；心衰時切換為糖。", exp_en:"Heart prefers FAs; switches to glucose in failure."},
          {type:"multi", stem:"以下哪些是代謝感測器？（多選）", stem_en:"Which are metabolic sensors? (multi)",
            A:"AMPK", A_en:"AMPK",
            B:"mTOR", B_en:"mTOR",
            C:"SIRT1", C_en:"SIRT1",
            D:"HIF-1α", D_en:"HIF-1α",
            ans:["A","B","C","D"], exp:"四大代謝感測器：能量 / 增長 / NAD⁺ / 氧。", exp_en:"Four sensors: energy, growth, NAD⁺, oxygen."},
          {type:"multi", stem:"哪些是胰島素的代謝效應？（多選）", stem_en:"Which are insulin effects? (multi)",
            A:"激活糖解", A_en:"Activates glycolysis",
            B:"促肝醣合成", B_en:"Promotes glycogen synthesis",
            C:"促脂肪合成", C_en:"Promotes lipogenesis",
            D:"激活糖質新生", D_en:"Activates gluconeogenesis",
            ans:["A","B","C"], exp:"胰島素抑制糖質新生。", exp_en:"Insulin inhibits gluconeogenesis."},
          {type:"tf", stem:"運動時 AMPK 被激活。", stem_en:"Exercise activates AMPK.",
            ans:"T", exp:"運動消耗 ATP → AMP 累積 → AMPK 激活。", exp_en:"Exercise depletes ATP → AMP rises → AMPK activates."},
          {type:"tf", stem:"GLP-1 受體激動劑（semaglutide）是 RTK 路徑。", stem_en:"GLP-1 receptor agonists (semaglutide) signal through RTK.",
            ans:"F", exp:"GLP-1 受體是 GPCR (Gαs 路徑)，非 RTK。", exp_en:"GLP-1R is a GPCR (Gαs path), not RTK."},
        ]
      },
      {
        id: "ch14", title: "Ch.14 訊息傳遞與第二訊息", title_en: "Ch.14 Signal Transduction",
        block: "D", questions: [
          {type:"single", stem:"霍亂毒素如何造成腹瀉？", stem_en:"How does cholera toxin cause diarrhea?",
            A:"破壞腸黏膜", A_en:"Damages mucosa",
            B:"干擾糖吸收", B_en:"Inhibits glucose uptake",
            C:"ADP-核糖化 Gαs → 鎖死活化 → cAMP 持續高 → CFTR 開水流出", C_en:"ADP-ribosylates Gαs → locks active → high cAMP → CFTR opens, water exits",
            D:"增加食慾", D_en:"Increases appetite",
            ans:"C", exp:"霍亂毒素的經典機制。", exp_en:"Classic cholera toxin mechanism."},
          {type:"single", stem:"RTK 啟動的標準步驟？", stem_en:"Standard RTK activation steps?",
            A:"直接磷酸化 ATP", A_en:"Phosphorylates ATP directly",
            B:"跨膜七次", B_en:"Spans membrane 7×",
            C:"配體誘導二聚化 → 自磷酸化 Tyr → SH2/PTB 招募", C_en:"Ligand dimerization → Tyr autophosphorylation → SH2/PTB recruitment",
            D:"用 cAMP", D_en:"Uses cAMP",
            ans:"C", exp:"EGFR、insulin R、PDGFR 等典型 RTK 機制。", exp_en:"Canonical mechanism for EGFR, insulin R, PDGFR."},
          {type:"single", stem:"Sildenafil（偉哥）作用？", stem_en:"Sildenafil mechanism?",
            A:"激活 cAMP", A_en:"Activates cAMP",
            B:"抑 PDE5 → cGMP↑ → 平滑肌鬆弛", B_en:"Inhibits PDE5 → cGMP↑ → smooth muscle relaxation",
            C:"增睪固酮", C_en:"Raises testosterone",
            D:"直接結合受體", D_en:"Binds receptor directly",
            ans:"B", exp:"PDE5 抑制讓 cGMP 不被降解。", exp_en:"PDE5 inhibition lets cGMP accumulate."},
          {type:"single", stem:"GPCR 訊息傳遞的「放大」可達多少倍？", stem_en:"GPCR signaling amplification can reach?",
            A:"~10×", A_en:"~10×", B:"~100×", B_en:"~100×",
            C:"~10⁶ 倍", C_en:"~10⁶×", D:"~10²×", D_en:"~10²×",
            ans:"C", exp:"激素 → 多個 G 蛋白 → 多個 cAMP → 多個 PKA → 多個受質。", exp_en:"Hormone → many G proteins → many cAMPs → many PKAs → many substrates."},
          {type:"single", stem:"Gαq 路徑啟動什麼？", stem_en:"Gαq pathway activates?",
            A:"AC → cAMP", A_en:"AC → cAMP",
            B:"PLCβ → IP3 + DAG → Ca²⁺ + PKC", B_en:"PLCβ → IP3 + DAG → Ca²⁺ + PKC",
            C:"RTK", C_en:"RTK",
            D:"JAK", D_en:"JAK",
            ans:"B", exp:"Gαq 經典產 IP3/DAG/Ca²⁺。", exp_en:"Gαq classically produces IP3/DAG/Ca²⁺."},
          {type:"single", stem:"PI3K 將什麼脂類磷酸化？", stem_en:"PI3K phosphorylates which lipid?",
            A:"PIP2 → PIP3", A_en:"PIP2 → PIP3",
            B:"PE → PS", B_en:"PE → PS",
            C:"PC → DAG", C_en:"PC → DAG",
            D:"膽固醇", D_en:"Cholesterol",
            ans:"A", exp:"PI3K 將 PIP2 磷酸化為 PIP3，招募 AKT。", exp_en:"PI3K phosphorylates PIP2 to PIP3, recruiting AKT."},
          {type:"multi", stem:"以下哪些是 GPCR 標靶藥物例子？（多選）", stem_en:"Which are GPCR-targeted drugs? (multi)",
            A:"β 阻斷劑（如 propranolol）", A_en:"β-blockers (e.g. propranolol)",
            B:"GLP-1 激動劑 (semaglutide)", B_en:"GLP-1 agonists (semaglutide)",
            C:"嗎啡（μ-opioid）", C_en:"Morphine (μ-opioid)",
            D:"Imatinib (BCR-ABL)", D_en:"Imatinib (BCR-ABL)",
            ans:["A","B","C"], exp:"Imatinib 是 RTK 抑制劑，不是 GPCR。", exp_en:"Imatinib targets RTK, not GPCR."},
          {type:"multi", stem:"哪些癌症通路常被過度激活？（多選）", stem_en:"Which pathways are often hyperactivated in cancer? (multi)",
            A:"RAS-RAF-MEK-ERK (MAPK)", A_en:"RAS-RAF-MEK-ERK (MAPK)",
            B:"PI3K-AKT-mTOR", B_en:"PI3K-AKT-mTOR",
            C:"JAK-STAT", C_en:"JAK-STAT",
            D:"DNA 複製抑制", D_en:"DNA replication inhibition",
            ans:["A","B","C"], exp:"D 是抑制（不是激活）。", exp_en:"D is inhibition, not activation."},
          {type:"tf", stem:"PTEN 是 PI3K-AKT 路徑的腫瘤抑制因子。", stem_en:"PTEN is a tumor suppressor in the PI3K-AKT pathway.",
            ans:"T", exp:"PTEN 將 PIP3 去磷酸化回 PIP2，下調 AKT。", exp_en:"PTEN dephosphorylates PIP3 to PIP2, downregulating AKT."},
          {type:"tf", stem:"β-arrestin 用於延長 GPCR 訊息。", stem_en:"β-arrestin extends GPCR signaling.",
            ans:"F", exp:"β-arrestin 終止 GPCR 訊息並引發內吞。", exp_en:"β-arrestin terminates GPCR signaling and triggers internalization."},
        ]
      },
      {
        id: "ch15", title: "Ch.15 中心法則的化學", title_en: "Ch.15 Central Dogma Chemistry",
        block: "D", questions: [
          {type:"single", stem:"DNA pol 的三層保真機制？", stem_en:"DNA pol three-layer fidelity?",
            A:"只有一層", A_en:"Only one",
            B:"兩層", B_en:"Two",
            C:"基質選擇 + 3'→5' 校對 + MMR（總錯誤率 10⁻⁹）", C_en:"Substrate selection + 3'→5' proofread + MMR (total 10⁻⁹)",
            D:"五層", D_en:"Five",
            ans:"C", exp:"三層機制把錯誤率從 10⁻⁴ 降至 10⁻⁹。", exp_en:"Three layers drop errors from 10⁻⁴ to 10⁻⁹."},
          {type:"single", stem:"核糖體的肽鍵催化中心由什麼組成？", stem_en:"Ribosome's peptidyl transferase center is?",
            A:"蛋白質酶", A_en:"Protein enzyme",
            B:"23S/28S rRNA（ribozyme）", B_en:"23S/28S rRNA (ribozyme)",
            C:"tRNA", C_en:"tRNA",
            D:"mRNA", D_en:"mRNA",
            ans:"B", exp:"Steitz/Yonath 等 2009 Nobel：核糖體是 ribozyme。", exp_en:"Steitz/Yonath 2009 Nobel: ribosome is a ribozyme."},
          {type:"single", stem:"K48 與 K63 多元泛素的差別？", stem_en:"K48 vs K63 polyubiquitin?",
            A:"相同", A_en:"Same",
            B:"都導致降解", B_en:"Both → degradation",
            C:"K48 → 蛋白酶體降解；K63 → 訊息傳遞、DNA 修復", C_en:"K48 → proteasomal degradation; K63 → signaling, DNA repair",
            D:"K63 降解", D_en:"K63 → degradation",
            ans:"C", exp:"不同連接位置控制泛素鏈的命運。", exp_en:"Different linkages control ubiquitin chain fate."},
          {type:"single", stem:"端粒酶為什麼是重要的？", stem_en:"Why is telomerase important?",
            A:"分解 DNA", A_en:"Breaks DNA",
            B:"逆轉錄酶 + RNA 模板加長端粒，解決末端複製問題", B_en:"RT + RNA template extends telomeres, solving end-replication problem",
            C:"轉錄 mRNA", C_en:"Transcribes mRNA",
            D:"剪接 RNA", D_en:"Splices RNA",
            ans:"B", exp:"線性染色體末端因 RNA 引子無法移除會縮短；端粒酶補救。", exp_en:"Linear chromosome ends shorten because final RNA primer can't be removed; telomerase rescues."},
          {type:"single", stem:"剪接體（spliceosome）的催化中心是什麼？", stem_en:"Spliceosome catalytic core?",
            A:"蛋白質酶", A_en:"Protein enzyme",
            B:"U2/U6 snRNA（ribozyme）", B_en:"U2/U6 snRNA (ribozyme)",
            C:"DNA pol", C_en:"DNA pol",
            D:"金屬離子", D_en:"Metal ion only",
            ans:"B", exp:"剪接體是另一個 ribozyme。", exp_en:"Spliceosome is another ribozyme."},
          {type:"single", stem:"組蛋白尾部的乙醯化效應？", stem_en:"Effect of histone tail acetylation?",
            A:"染色質壓縮", A_en:"Chromatin condensation",
            B:"中和 Lys +1 電荷 → DNA 結合減弱 → 染色質開啟", B_en:"Neutralizes Lys + charge → weaker DNA binding → chromatin opens",
            C:"造成突變", C_en:"Causes mutation",
            D:"剪接", D_en:"Splicing",
            ans:"B", exp:"HAT 加乙醯化開啟基因；HDAC 移除使染色質緊。", exp_en:"HAT activates genes; HDAC compacts chromatin."},
          {type:"multi", stem:"以下哪些是真核 mRNA 加工事件？（多選）", stem_en:"Eukaryotic mRNA processing events? (multi)",
            A:"5' cap", A_en:"5' cap",
            B:"剪接", B_en:"Splicing",
            C:"3' polyA", C_en:"3' polyA",
            D:"DNA 複製", D_en:"DNA replication",
            ans:["A","B","C"], exp:"DNA 複製不是 mRNA 加工。", exp_en:"DNA replication is not mRNA processing."},
          {type:"multi", stem:"哪些 PTM 不改變胺基酸電荷？（多選）", stem_en:"Which PTMs don't change AA charge? (multi)",
            A:"甲基化", A_en:"Methylation",
            B:"糖基化", B_en:"Glycosylation",
            C:"磷酸化", C_en:"Phosphorylation",
            D:"乙醯化（在 Lys）", D_en:"Acetylation (on Lys)",
            ans:["A","B"], exp:"磷酸化加 -2、Lys 乙醯化中和 +1。", exp_en:"Phosphorylation adds −2; Lys acetylation neutralizes +1."},
          {type:"tf", stem:"DNA pol 與 RNA pol 都用兩個金屬離子催化機制。", stem_en:"Both DNA and RNA pol use two-metal-ion catalysis.",
            ans:"T", exp:"兩者活位點結構相似。", exp_en:"Both share similar active-site architecture."},
          {type:"tf", stem:"abortion mRNA 疫苗利用 m1Ψ 是為了增加翻譯。", stem_en:"mRNA vaccines use m1Ψ to boost translation.",
            ans:"T", exp:"並同時避開 TLR/RIG-I 免疫識別。", exp_en:"Also evades TLR/RIG-I sensing."},
        ]
      },
      {
        id: "ch16", title: "Ch.16 臨床生化", title_en: "Ch.16 Clinical Biochemistry",
        block: "E", questions: [
          {type:"single", stem:"HbA1c 反映多久平均血糖？", stem_en:"HbA1c reflects how long?",
            A:"1 天", A_en:"1 day", B:"1 週", B_en:"1 week",
            C:"8–12 週", C_en:"8–12 weeks", D:"1 年", D_en:"1 year",
            ans:"C", exp:"受紅血球壽命（120 天）限制。", exp_en:"Bounded by RBC lifespan (120 days)."},
          {type:"single", stem:"鐮刀型紅血球的分子原因？", stem_en:"Molecular cause of sickle cell?",
            A:"α-globin 缺失", A_en:"α-globin deletion",
            B:"鐵中毒", B_en:"Iron toxicity",
            C:"β-globin Glu6Val 突變 → 脫氧聚合", C_en:"β-globin Glu6Val mutation → deoxy polymerization",
            D:"RBC 太大", D_en:"Large RBC",
            ans:"C", exp:"單一胺基酸突變造成蛋白聚合。", exp_en:"Single AA change drives protein polymerization."},
          {type:"single", stem:"痛風急性發作為何劇痛？", stem_en:"Why is acute gout so painful?",
            A:"尿酸刺激神經", A_en:"Urate stimulates nerves",
            B:"MSU 晶體激活 NLRP3 inflammasome → IL-1β 釋放", B_en:"MSU crystals activate NLRP3 inflammasome → IL-1β release",
            C:"細菌感染", C_en:"Bacterial infection",
            D:"缺血", D_en:"Ischemia",
            ans:"B", exp:"NLRP3-IL-1β 路徑造成劇烈炎症。", exp_en:"NLRP3-IL-1β pathway drives intense inflammation."},
          {type:"single", stem:"PKU 的關鍵酶缺陷？", stem_en:"Key enzyme defect in PKU?",
            A:"GALT", A_en:"GALT",
            B:"PAH（苯丙胺酸羥化酶）", B_en:"PAH (phenylalanine hydroxylase)",
            C:"OTC", C_en:"OTC",
            D:"BCKDH", D_en:"BCKDH",
            ans:"B", exp:"PAH 缺陷無法將 Phe 轉為 Tyr。", exp_en:"PAH deficiency blocks Phe → Tyr."},
          {type:"single", stem:"GLP-1 受體激動劑的核心應用？", stem_en:"Core use of GLP-1 receptor agonists?",
            A:"高血壓", A_en:"Hypertension",
            B:"糖尿病 + 顯著減重效果", B_en:"Diabetes + dramatic weight loss",
            C:"高膽固醇", C_en:"High cholesterol",
            D:"骨質疏鬆", D_en:"Osteoporosis",
            ans:"B", exp:"semaglutide、tirzepatide 是 2024 經典代表。", exp_en:"Semaglutide, tirzepatide are 2024 leaders."},
          {type:"single", stem:"AST/ALT 升高最直接反映？", stem_en:"Elevated AST/ALT directly reflect?",
            A:"心衰", A_en:"Heart failure",
            B:"肝細胞損傷", B_en:"Hepatocyte damage",
            C:"腎衰", C_en:"Renal failure",
            D:"糖尿病", D_en:"Diabetes",
            ans:"B", exp:"ALT 較肝特異，AST 也見於心/肌。", exp_en:"ALT is more liver-specific; AST also in heart/muscle."},
          {type:"multi", stem:"以下哪些屬於 IEM 的新生兒篩檢項目？（多選）", stem_en:"Which are newborn-screened IEMs? (multi)",
            A:"PKU", A_en:"PKU",
            B:"半乳糖血症", B_en:"Galactosemia",
            C:"楓糖尿症 (MSUD)", C_en:"MSUD",
            D:"X 連鎖 ALD（依國家）", D_en:"X-linked ALD (depends on country)",
            ans:["A","B","C","D"], exp:"皆為常規或擴展篩檢項目。", exp_en:"All are standard or expanded screening items."},
          {type:"multi", stem:"以下何者為糖尿病併發症？（多選）", stem_en:"Which are diabetes complications? (multi)",
            A:"視網膜病變", A_en:"Retinopathy",
            B:"腎病變", B_en:"Nephropathy",
            C:"神經病變", C_en:"Neuropathy",
            D:"急性盲腸炎", D_en:"Acute appendicitis",
            ans:["A","B","C"], exp:"AGEs 慢性損傷血管與神經。", exp_en:"AGEs chronically damage vessels and nerves."},
          {type:"tf", stem:"Casgevy (2023 FDA) 是首個 CRISPR-Cas9 治療鐮刀症的基因編輯藥物。", stem_en:"Casgevy (2023 FDA) is the first CRISPR therapy for sickle cell.",
            ans:"T", exp:"開創 CRISPR 治療時代。", exp_en:"Inaugurated the CRISPR therapy era."},
          {type:"tf", stem:"Trikafta 為三藥組合，治療囊狀纖維化。", stem_en:"Trikafta is a triple combo for cystic fibrosis.",
            ans:"T", exp:"elexacaftor + tezacaftor + ivacaftor。", exp_en:"Elexacaftor + tezacaftor + ivacaftor."},
        ]
      },
      {
        id: "ch17", title: "Ch.17 生化學與藥物設計", title_en: "Ch.17 Drug Design",
        block: "E", questions: [
          {type:"single", stem:"PROTAC 與傳統抑制劑的核心差別？", stem_en:"PROTAC vs classical inhibitor core difference?",
            A:"PROTAC 永久結合", A_en:"PROTAC binds permanently",
            B:"都需要高親和力", B_en:"Both need high affinity",
            C:"傳統 = 佔據活位點；PROTAC = 引向 E3 連接酶降解（事件驅動）", C_en:"Classical occupies; PROTAC drives degradation (event-driven)",
            D:"PROTAC 不是分子", D_en:"PROTAC isn't a molecule",
            ans:"C", exp:"PROTAC 不需高親和力可催化降解。", exp_en:"PROTAC needs no high affinity — catalyzes degradation."},
          {type:"single", stem:"Sotorasib (Lumakras) 的關鍵化學？", stem_en:"Key chemistry of sotorasib?",
            A:"非共價 KRAS-WT", A_en:"Non-covalent KRAS-WT",
            B:"利用 KRAS-G12C 突變的獨特 Cys 形成共價鍵", B_en:"Uses unique Cys of KRAS-G12C to form covalent bond",
            C:"抗體", C_en:"Antibody",
            D:"siRNA", D_en:"siRNA",
            ans:"B", exp:"打破 KRAS「不可成藥」的觀念。", exp_en:"Broke the 'undruggable KRAS' paradigm."},
          {type:"single", stem:"細胞內標靶該選何模式？", stem_en:"Modality for intracellular target?",
            A:"抗體", A_en:"Antibody",
            B:"CAR-T", B_en:"CAR-T",
            C:"雙特異抗體", C_en:"Bispecific antibody",
            D:"小分子 / PROTAC / 分子膠（穿膜）", D_en:"Small molecule / PROTAC / molecular glue (permeable)",
            ans:"D", exp:"抗體不過細胞膜。", exp_en:"Antibodies don't cross membranes."},
          {type:"single", stem:"Lipinski Rule of 5 不包括下列哪一項？", stem_en:"Lipinski's RoF doesn't include?",
            A:"MW < 500", A_en:"MW < 500",
            B:"LogP < 5", B_en:"LogP < 5",
            C:"HBD ≤ 5", C_en:"HBD ≤ 5",
            D:"溶解度 ≥ 10 mg/mL", D_en:"Solubility ≥ 10 mg/mL",
            ans:"D", exp:"Lipinski 是 MW、LogP、HBD、HBA、Rotatable bonds，不是溶解度。", exp_en:"Lipinski 5: MW, LogP, HBD, HBA, RotB — not solubility directly."},
          {type:"single", stem:"AlphaFold 3 對藥物設計最大影響？", stem_en:"Biggest impact of AF3 on drug discovery?",
            A:"完全取代實驗結構", A_en:"Fully replaces experimental structures",
            B:"預測蛋白-配體複合物，加速「初步篩選+假設」", B_en:"Predicts protein-ligand complexes, accelerating initial screening + hypothesis",
            C:"不影響", C_en:"No impact",
            D:"只能預測蛋白單體", D_en:"Only monomers",
            ans:"B", exp:"PoseBusters 顯示 ~50% 優於傳統 docking，但實驗仍金標準。", exp_en:"~50% better than docking on PoseBusters; experiment remains gold standard."},
          {type:"single", stem:"FBDD 比 HTS 有何優勢？", stem_en:"FBDD advantage over HTS?",
            A:"比 HTS 慢", A_en:"Slower than HTS",
            B:"片段命中率比 HTS 高 100×", B_en:"Fragment hit rate ~100× higher than HTS",
            C:"不需要結構", C_en:"No structure needed",
            D:"無法產生臨床藥物", D_en:"Cannot produce drugs",
            ans:"B", exp:"venetoclax、vemurafenib 等多個臨床藥物源自 FBDD。", exp_en:"Venetoclax, vemurafenib etc. came from FBDD."},
          {type:"multi", stem:"以下哪些是現代藥物模式？（多選）", stem_en:"Which are modern drug modalities? (multi)",
            A:"小分子", A_en:"Small molecules",
            B:"抗體", B_en:"Antibodies",
            C:"ADC", C_en:"ADC",
            D:"mRNA 疫苗", D_en:"mRNA vaccines",
            ans:["A","B","C","D"], exp:"四者皆為現代藥物模式。", exp_en:"All four are modern modalities."},
          {type:"multi", stem:"以下哪些是 2025 PROTAC 設計趨勢？（多選）", stem_en:"2025 PROTAC design trends? (multi)",
            A:"Trivalent PROTAC", A_en:"Trivalent PROTAC",
            B:"光開關 PROTAC（PHOTAC）", B_en:"Photoswitchable (PHOTAC)",
            C:"新 E3 連接酶（超越 cereblon/VHL）", C_en:"Novel E3 ligases (beyond cereblon/VHL)",
            D:"取代抗體", D_en:"Replace antibodies",
            ans:["A","B","C"], exp:"D 並非 PROTAC 設計趨勢。", exp_en:"D isn't a PROTAC trend."},
          {type:"tf", stem:"分子膠通常比 PROTAC 分子量小、更口服。", stem_en:"Molecular glues are usually smaller and more oral than PROTACs.",
            ans:"T", exp:"分子膠單頭、小尺寸；PROTAC 雙頭較大。", exp_en:"Glues are monovalent and small; PROTACs are bifunctional and larger."},
          {type:"tf", stem:"Lipinski 規則對所有藥物模式皆嚴格適用。", stem_en:"Lipinski's rules apply strictly to all drug modalities.",
            ans:"F", exp:"生物製劑、PROTAC、肽等通常超出 Lipinski 範圍。", exp_en:"Biologics, PROTACs, peptides often violate Lipinski."},
        ]
      },
      {
        id: "ch18", title: "Ch.18 現代生化技術與 AI", title_en: "Ch.18 Modern Techniques & AI",
        block: "E", questions: [
          {type:"single", stem:"HDX-MS 的主要用途？", stem_en:"Main use of HDX-MS?",
            A:"序列鑑定", A_en:"Sequence ID",
            B:"定量蛋白", B_en:"Protein quantification",
            C:"測蛋白動態、結合界面、變構", C_en:"Protein dynamics, interfaces, allostery",
            D:"細胞篩選", D_en:"Cell screening",
            ans:"C", exp:"氫氘交換率反映局部結構穩定性。", exp_en:"H/D exchange rates reflect local structural stability."},
          {type:"single", stem:"RFdiffusion 是什麼？", stem_en:"What is RFdiffusion?",
            A:"結構預測", A_en:"Structure predictor",
            B:"擴散模型「從零設計」新蛋白骨架（Baker lab）", B_en:"Diffusion model for de novo protein backbone design (Baker lab)",
            C:"影像工具", C_en:"Image tool",
            D:"NMR 方法", D_en:"NMR method",
            ans:"B", exp:"2023 Nature 突破——AI 設計蛋白的里程碑。", exp_en:"2023 Nature breakthrough — milestone in AI protein design."},
          {type:"single", stem:"為什麼 IDP 是 AlphaFold 弱項？", stem_en:"Why are IDPs an AF weak spot?",
            A:"太小", A_en:"Too small",
            B:"無序列", B_en:"No sequence",
            C:"本質無結構/構象集合，AF 假設不適用", C_en:"Intrinsically disordered — AF's single-fold assumption fails",
            D:"訓練集無", D_en:"Absent from training set",
            ans:"C", exp:"需用 NMR、HDX-MS、SAXS 補充。", exp_en:"Use NMR, HDX-MS, SAXS instead."},
          {type:"single", stem:"MSI Level 1 代謝物鑑定需要？", stem_en:"MSI Level 1 metabolite ID requires?",
            A:"只需精確 m/z", A_en:"Just accurate m/z",
            B:"標品比對（RT + MS/MS）", B_en:"Standard match (RT + MS/MS)",
            C:"AI 預測", C_en:"AI prediction",
            D:"基因組註解", D_en:"Genome annotation",
            ans:"B", exp:"必須用標品確認 retention time 與 MS/MS 譜圖。", exp_en:"Must confirm RT and MS/MS spectrum with standards."},
          {type:"single", stem:"哪一個是「分支鏈胺基酸」與糖尿病相關的代謝體 biomarker？", stem_en:"Which is a metabolomic biomarker linked to T2DM?",
            A:"BCAA（Leu/Ile/Val）", A_en:"BCAAs (Leu/Ile/Val)",
            B:"棕櫚酸", B_en:"Palmitate",
            C:"葡萄糖", C_en:"Glucose",
            D:"乳酸", D_en:"Lactate",
            ans:"A", exp:"BCAAs 升高為糖尿病前期重要 signature。", exp_en:"Elevated BCAAs are a key prediabetic signature."},
          {type:"single", stem:"哪一個 AI 工具開源、可作為 AlphaFold 3 的替代？", stem_en:"Which open-source tool is an AF3 alternative?",
            A:"AlphaFold 1", A_en:"AlphaFold 1",
            B:"Boltz-1 (2024)", B_en:"Boltz-1 (2024)",
            C:"BLAST", C_en:"BLAST",
            D:"PyMOL", D_en:"PyMOL",
            ans:"B", exp:"Boltz-1 是 MIT 2024 開源，重現 AF3 能力。", exp_en:"Boltz-1 is MIT 2024 open-source, reproducing AF3 capabilities."},
          {type:"multi", stem:"以下哪些是常見的質譜實驗方法？（多選）", stem_en:"Which are common MS methods? (multi)",
            A:"LC-MS/MS（DDA）", A_en:"LC-MS/MS (DDA)",
            B:"DIA", B_en:"DIA",
            C:"TMT 多重定量", C_en:"TMT multiplex quant",
            D:"DNA 定序", D_en:"DNA sequencing",
            ans:["A","B","C"], exp:"DNA 定序不是質譜。", exp_en:"DNA sequencing is not MS."},
          {type:"multi", stem:"以下哪些屬於 oncometabolites？（多選）", stem_en:"Which are oncometabolites? (multi)",
            A:"2-Hydroxyglutarate (IDH-mut)", A_en:"2-HG (IDH-mut)",
            B:"Fumarate (HLRCC)", B_en:"Fumarate (HLRCC)",
            C:"Succinate (SDH-mut)", C_en:"Succinate (SDH-mut)",
            D:"Pyruvate", D_en:"Pyruvate",
            ans:["A","B","C"], exp:"Pyruvate 是正常代謝物。", exp_en:"Pyruvate is a normal metabolite."},
          {type:"tf", stem:"Cryo-ET 可在細胞內原位觀察大分子結構。", stem_en:"Cryo-ET enables in-cell macromolecular imaging.",
            ans:"T", exp:"FIB-SEM milling + 電子斷層達 4-10 Å。", exp_en:"FIB-SEM milling + electron tomography achieves 4-10 Å."},
          {type:"tf", stem:"AI 完全取代了實驗結構生物學。", stem_en:"AI has fully replaced experimental structural biology.",
            ans:"F", exp:"實驗仍為金標準；AI 是加速工具非取代。", exp_en:"Experiment is still gold standard; AI accelerates, doesn't replace."},
        ]
      },
    ]
  }
};
